///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace T4._
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UploadSmt recording.
    /// </summary>
    [TestModule("7c7f1dfa-45b3-49d6-893a-cff715db12af", ModuleType.Recording, 1)]
    public partial class UploadSmt : ITestModule
    {
        /// <summary>
        /// Holds an instance of the T4_2Repository repository.
        /// </summary>
        public static T4_2Repository repo = T4_2Repository.Instance;

        static UploadSmt instance = new UploadSmt();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UploadSmt()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UploadSmt Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.UploadOrDrop' at 69;34.", repo.FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.UploadOrDropInfo, new RecordItemIndex(0));
            repo.FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.UploadOrDrop.Click("69;34");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.File' at 47;14.", repo.FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.FileInfo, new RecordItemIndex(1));
            repo.FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.File.Click("47;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.Tree100' at 26;18.", repo.Open.Tree100Info, new RecordItemIndex(2));
            repo.Open.Tree100.Click("26;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.ListItem2' at 43;12.", repo.Open.ListItem2Info, new RecordItemIndex(3));
            repo.Open.ListItem2.Click("43;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.ButtonOpen' at 38;17.", repo.Open.ButtonOpenInfo, new RecordItemIndex(4));
            repo.Open.ButtonOpen.Click("38;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Uploaded to') on item 'FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.UploadedTo'.", repo.FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.UploadedToInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.UploadedToInfo, "Text", "Uploaded to");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
