///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace T12
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LimitLengthEmail recording.
    /// </summary>
    [TestModule("096ad571-7368-4efe-b4be-c7812f606932", ModuleType.Recording, 1)]
    public partial class LimitLengthEmail : ITestModule
    {
        /// <summary>
        /// Holds an instance of the T12Repository repository.
        /// </summary>
        public static T12Repository repo = T12Repository.Instance;

        static LimitLengthEmail instance = new LimitLengthEmail();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LimitLengthEmail()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LimitLengthEmail Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SusiEmail40801742546270514' at 75;23.", repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SusiEmail40801742546270514Info, new RecordItemIndex(0));
            repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SusiEmail40801742546270514.Click("75;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'kasjdhfasjkdfsjkdfgsjkdhgfsuyuiwetr{y up}hjdfgasdgyuwegfjsadgfuwygfjashdgfauyiegfashjdgfkjashdg{k up}fkjasdgfjkahsdgfkjahsg{k up}dfjkahsdgfjkashgdfjkahsgdfjkashdgfjkhsadgfkjashgdfkjasghdfjkhasd{j up}gfjkashdgfkjasdgfkjsahdgfkjhsdgfkjasgdfjksahdgfjksahg{j up}fjakshgfjkahsgdfjkashd{j up}gfjkshdgfkjshkdgfjksahg{j up}df{s up}jkshgdfjashgfjhsgdfjkasgdfjkasgfsjkgfsjkgfjkasfkjasfgkshdfgjksadhfg{j up}skjdhfgs{RShiftKey down}{2 down}{RShiftKey up}gmail.com' with focus on 'LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SusiEmail40801742546270514'.", repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SusiEmail40801742546270514Info, new RecordItemIndex(1));
            repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SusiEmail40801742546270514.PressKeys("kasjdhfasjkdfsjkdfgsjkdhgfsuyuiwetr{y up}hjdfgasdgyuwegfjsadgfuwygfjashdgfauyiegfashjdgfkjashdg{k up}fkjasdgfjkahsdgfkjahsg{k up}dfjkahsdgfjkashgdfjkahsgdfjkashdgfjkhsadgfkjashgdfkjasghdfjkhasd{j up}gfjkashdgfkjasdgfkjsahdgfkjhsdgfkjasgdfjksahdgfjksahg{j up}fjakshgfjkahsgdfjkashd{j up}gfjkshdgfkjshkdgfjksahg{j up}df{s up}jkshgdfjashgfjhsgdfjkasgdfjkasgfsjkgfsjkgfjkasfkjasfgkshdfgjksadhfg{j up}skjdhfgs{RShiftKey down}{2 down}{RShiftKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.Continue' at 24;11.", repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.ContinueInfo, new RecordItemIndex(2));
            repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.Continue.Click("24;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Invalid email') on item 'LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.InvalidEmail'.", repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.InvalidEmailInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.InvalidEmailInfo, "Text", "Invalid email");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
