///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T12
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T12Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("40f8059f-2da5-42b1-baa8-c56d50485143")]
    public partial class T12Repository : RepoGenBaseFolder
    {
        static T12Repository instance = new T12Repository();
        T12RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T12RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder _logindropboxpersonalmicrosofte;

        /// <summary>
        /// Gets the singleton class instance representing the T12Repository element repository.
        /// </summary>
        [RepositoryFolder("40f8059f-2da5-42b1-baa8-c56d50485143")]
        public static T12Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T12Repository() 
            : base("T12Repository", "/", null, 0, false, "40f8059f-2da5-42b1-baa8-c56d50485143", ".\\RepositoryImages\\T12Repository40f8059f.rximgres")
        {
            _applicationundertest = new T12RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _logindropboxpersonalmicrosofte = new T12RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("40f8059f-2da5-42b1-baa8-c56d50485143")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("1177c95f-1d00-4c2f-b5db-68ceaa7487b6")]
        public virtual T12RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The LoginDropboxPersonalMicrosoftE folder.
        /// </summary>
        [RepositoryFolder("872c0831-ac28-402c-89ae-a4046a67da8d")]
        public virtual T12RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder LoginDropboxPersonalMicrosoftE
        {
            get { return _logindropboxpersonalmicrosofte; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T12RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("1177c95f-1d00-4c2f-b5db-68ceaa7487b6")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "1177c95f-1d00-4c2f-b5db-68ceaa7487b6", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1177c95f-1d00-4c2f-b5db-68ceaa7487b6")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1177c95f-1d00-4c2f-b5db-68ceaa7487b6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The LoginDropboxPersonalMicrosoftEAppFolder folder.
        /// </summary>
        [RepositoryFolder("872c0831-ac28-402c-89ae-a4046a67da8d")]
        public partial class LoginDropboxPersonalMicrosoftEAppFolder : RepoGenBaseFolder
        {
            T12RepositoryFolders.SidebarContentsSplitViewFolder _sidebarcontentssplitview;

            /// <summary>
            /// Creates a new LoginDropboxPersonalMicrosoftE  folder.
            /// </summary>
            public LoginDropboxPersonalMicrosoftEAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginDropboxPersonalMicrosoftE", "/form[@title>'Login - Dropbox - Personal']", parentFolder, 30000, null, true, "872c0831-ac28-402c-89ae-a4046a67da8d", "")
            {
                _sidebarcontentssplitview = new T12RepositoryFolders.SidebarContentsSplitViewFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("872c0831-ac28-402c-89ae-a4046a67da8d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("872c0831-ac28-402c-89ae-a4046a67da8d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SidebarContentsSplitView folder.
            /// </summary>
            [RepositoryFolder("21596eb2-fb1c-4324-ba7e-1761d790a5cc")]
            public virtual T12RepositoryFolders.SidebarContentsSplitViewFolder SidebarContentsSplitView
            {
                get { return _sidebarcontentssplitview; }
            }
        }

        /// <summary>
        /// The SidebarContentsSplitViewFolder folder.
        /// </summary>
        [RepositoryFolder("21596eb2-fb1c-4324-ba7e-1761d790a5cc")]
        public partial class SidebarContentsSplitViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _invalidemailInfo;
            RepoItemInfo _susiemail40801742546270514Info;
            RepoItemInfo _continueInfo;

            /// <summary>
            /// Creates a new SidebarContentsSplitView  folder.
            /// </summary>
            public SidebarContentsSplitViewFolder(RepoGenBaseFolder parentFolder) :
                    base("SidebarContentsSplitView", "container[@name>'Login - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']", parentFolder, 30000, null, false, "21596eb2-fb1c-4324-ba7e-1761d790a5cc", "")
            {
                _invalidemailInfo = new RepoItemInfo(this, "InvalidEmail", ".//container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//container/text[@name='Invalid email']", "", 30000, null, "723c7273-fe5f-4925-8ea4-545e950bf3d6");
                _susiemail40801742546270514Info = new RepoItemInfo(this, "SusiEmail40801742546270514", ".//container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//container[@classname='_field-input-wrapper_4srl7_50']/text[@automationid~'susi_email']", "", 30000, null, "3787780c-222c-4e3c-9e70-d326a280e354");
                _continueInfo = new RepoItemInfo(this, "Continue", "container[@orientation='None' and @iscontentelement='True']/?/?/container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Continue']/?/?/text[@name='Continue']", "", 30000, null, "1522f9b2-7dc0-431f-813c-b364141f6f61");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("21596eb2-fb1c-4324-ba7e-1761d790a5cc")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("21596eb2-fb1c-4324-ba7e-1761d790a5cc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InvalidEmail item.
            /// </summary>
            [RepositoryItem("723c7273-fe5f-4925-8ea4-545e950bf3d6")]
            public virtual Ranorex.Text InvalidEmail
            {
                get
                {
                    return _invalidemailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The InvalidEmail item info.
            /// </summary>
            [RepositoryItemInfo("723c7273-fe5f-4925-8ea4-545e950bf3d6")]
            public virtual RepoItemInfo InvalidEmailInfo
            {
                get
                {
                    return _invalidemailInfo;
                }
            }

            /// <summary>
            /// The SusiEmail40801742546270514 item.
            /// </summary>
            [RepositoryItem("3787780c-222c-4e3c-9e70-d326a280e354")]
            public virtual Ranorex.Text SusiEmail40801742546270514
            {
                get
                {
                    return _susiemail40801742546270514Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SusiEmail40801742546270514 item info.
            /// </summary>
            [RepositoryItemInfo("3787780c-222c-4e3c-9e70-d326a280e354")]
            public virtual RepoItemInfo SusiEmail40801742546270514Info
            {
                get
                {
                    return _susiemail40801742546270514Info;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("1522f9b2-7dc0-431f-813c-b364141f6f61")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("1522f9b2-7dc0-431f-813c-b364141f6f61")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
