///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace T6
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EmailNotExists recording.
    /// </summary>
    [TestModule("33f97a6f-cf68-41dc-84b0-d256ad63d8a7", ModuleType.Recording, 1)]
    public partial class EmailNotExists : ITestModule
    {
        /// <summary>
        /// Holds an instance of the T6Repository repository.
        /// </summary>
        public static T6Repository repo = T6Repository.Instance;

        static EmailNotExists instance = new EmailNotExists();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EmailNotExists()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EmailNotExists Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RegisterDropboxPersonalMicrosof.SidebarContentsSplitView.SusiEmail6192151393851142' at 126;26.", repo.RegisterDropboxPersonalMicrosof.SidebarContentsSplitView.SusiEmail6192151393851142Info, new RecordItemIndex(0));
            repo.RegisterDropboxPersonalMicrosof.SidebarContentsSplitView.SusiEmail6192151393851142.Click("126;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aduconchoxuytbg@gmail.com' with focus on 'RegisterDropboxPersonalMicrosof.SidebarContentsSplitView.SusiEmail6192151393851142'.", repo.RegisterDropboxPersonalMicrosof.SidebarContentsSplitView.SusiEmail6192151393851142Info, new RecordItemIndex(1));
            repo.RegisterDropboxPersonalMicrosof.SidebarContentsSplitView.SusiEmail6192151393851142.PressKeys("aduconchoxuytbg@gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RegisterDropboxPersonalMicrosof.SidebarContentsSplitView.Continue' at 40;11.", repo.RegisterDropboxPersonalMicrosof.SidebarContentsSplitView.ContinueInfo, new RecordItemIndex(2));
            repo.RegisterDropboxPersonalMicrosof.SidebarContentsSplitView.Continue.Click("40;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Sign up for free') on item 'RegisterDropboxPersonalMicrosof.SidebarContentsSplitView.SignUpForFree'.", repo.RegisterDropboxPersonalMicrosof.SidebarContentsSplitView.SignUpForFreeInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.RegisterDropboxPersonalMicrosof.SidebarContentsSplitView.SignUpForFreeInfo, "Text", "Sign up for free");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
