///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T6
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T6Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("61a13c41-d78a-473b-83ce-a2e7ace536f3")]
    public partial class T6Repository : RepoGenBaseFolder
    {
        static T6Repository instance = new T6Repository();
        T6RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T6RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder _registerdropboxpersonalmicrosof;

        /// <summary>
        /// Gets the singleton class instance representing the T6Repository element repository.
        /// </summary>
        [RepositoryFolder("61a13c41-d78a-473b-83ce-a2e7ace536f3")]
        public static T6Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T6Repository() 
            : base("T6Repository", "/", null, 0, false, "61a13c41-d78a-473b-83ce-a2e7ace536f3", ".\\RepositoryImages\\T6Repository61a13c41.rximgres")
        {
            _applicationundertest = new T6RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _registerdropboxpersonalmicrosof = new T6RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("61a13c41-d78a-473b-83ce-a2e7ace536f3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("fb0a5f9a-1421-4b6f-8f53-19ae164671d7")]
        public virtual T6RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosof folder.
        /// </summary>
        [RepositoryFolder("b1576193-7064-43d7-90ac-91330e375caf")]
        public virtual T6RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder RegisterDropboxPersonalMicrosof
        {
            get { return _registerdropboxpersonalmicrosof; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T6RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("fb0a5f9a-1421-4b6f-8f53-19ae164671d7")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "fb0a5f9a-1421-4b6f-8f53-19ae164671d7", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fb0a5f9a-1421-4b6f-8f53-19ae164671d7")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fb0a5f9a-1421-4b6f-8f53-19ae164671d7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosofAppFolder folder.
        /// </summary>
        [RepositoryFolder("b1576193-7064-43d7-90ac-91330e375caf")]
        public partial class RegisterDropboxPersonalMicrosofAppFolder : RepoGenBaseFolder
        {
            T6RepositoryFolders.SidebarContentsSplitViewFolder _sidebarcontentssplitview;

            /// <summary>
            /// Creates a new RegisterDropboxPersonalMicrosof  folder.
            /// </summary>
            public RegisterDropboxPersonalMicrosofAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterDropboxPersonalMicrosof", "/form[@title>'Register - Dropbox - Personal']", parentFolder, 30000, null, true, "b1576193-7064-43d7-90ac-91330e375caf", "")
            {
                _sidebarcontentssplitview = new T6RepositoryFolders.SidebarContentsSplitViewFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b1576193-7064-43d7-90ac-91330e375caf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b1576193-7064-43d7-90ac-91330e375caf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SidebarContentsSplitView folder.
            /// </summary>
            [RepositoryFolder("3a0b173f-3a94-44d6-beda-34acc9924c61")]
            public virtual T6RepositoryFolders.SidebarContentsSplitViewFolder SidebarContentsSplitView
            {
                get { return _sidebarcontentssplitview; }
            }
        }

        /// <summary>
        /// The SidebarContentsSplitViewFolder folder.
        /// </summary>
        [RepositoryFolder("3a0b173f-3a94-44d6-beda-34acc9924c61")]
        public partial class SidebarContentsSplitViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginorregisterpagecontentInfo;
            RepoItemInfo _signupforfreeInfo;
            RepoItemInfo _continueInfo;
            RepoItemInfo _susiemail6192151393851142Info;

            /// <summary>
            /// Creates a new SidebarContentsSplitView  folder.
            /// </summary>
            public SidebarContentsSplitViewFolder(RepoGenBaseFolder parentFolder) :
                    base("SidebarContentsSplitView", "container[@name>'Register - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']", parentFolder, 30000, null, false, "3a0b173f-3a94-44d6-beda-34acc9924c61", "")
            {
                _loginorregisterpagecontentInfo = new RepoItemInfo(this, "LoginOrRegisterPageContent", ".//container[@automationid='207343552']/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']", "", 30000, null, "3ffc2481-433b-4887-8947-b173e406f04c");
                _signupforfreeInfo = new RepoItemInfo(this, "SignUpForFree", ".//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']/?/?/text[@name='Sign up for free']", "", 30000, null, "5d797475-9944-48a1-978e-7f232fb5e5a7");
                _continueInfo = new RepoItemInfo(this, "Continue", "container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Continue']/?/?/text[@name='Continue']", "", 30000, null, "86e4d335-41d1-4f19-82d9-37959bfa51ec");
                _susiemail6192151393851142Info = new RepoItemInfo(this, "SusiEmail6192151393851142", "container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//text[@automationid~'susi_email']", "", 30000, null, "acb11041-c8d1-46ac-8b1d-7645d7ad3ec1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3a0b173f-3a94-44d6-beda-34acc9924c61")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3a0b173f-3a94-44d6-beda-34acc9924c61")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginOrRegisterPageContent item.
            /// </summary>
            [RepositoryItem("3ffc2481-433b-4887-8947-b173e406f04c")]
            public virtual Ranorex.Container LoginOrRegisterPageContent
            {
                get
                {
                    return _loginorregisterpagecontentInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The LoginOrRegisterPageContent item info.
            /// </summary>
            [RepositoryItemInfo("3ffc2481-433b-4887-8947-b173e406f04c")]
            public virtual RepoItemInfo LoginOrRegisterPageContentInfo
            {
                get
                {
                    return _loginorregisterpagecontentInfo;
                }
            }

            /// <summary>
            /// The SignUpForFree item.
            /// </summary>
            [RepositoryItem("5d797475-9944-48a1-978e-7f232fb5e5a7")]
            public virtual Ranorex.Text SignUpForFree
            {
                get
                {
                    return _signupforfreeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SignUpForFree item info.
            /// </summary>
            [RepositoryItemInfo("5d797475-9944-48a1-978e-7f232fb5e5a7")]
            public virtual RepoItemInfo SignUpForFreeInfo
            {
                get
                {
                    return _signupforfreeInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("86e4d335-41d1-4f19-82d9-37959bfa51ec")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("86e4d335-41d1-4f19-82d9-37959bfa51ec")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The SusiEmail6192151393851142 item.
            /// </summary>
            [RepositoryItem("acb11041-c8d1-46ac-8b1d-7645d7ad3ec1")]
            public virtual Ranorex.Text SusiEmail6192151393851142
            {
                get
                {
                    return _susiemail6192151393851142Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SusiEmail6192151393851142 item info.
            /// </summary>
            [RepositoryItemInfo("acb11041-c8d1-46ac-8b1d-7645d7ad3ec1")]
            public virtual RepoItemInfo SusiEmail6192151393851142Info
            {
                get
                {
                    return _susiemail6192151393851142Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
