///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T21
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T21Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c2bec75b-a956-4d53-aebd-693bb95c3de4")]
    public partial class T21Repository : RepoGenBaseFolder
    {
        static T21Repository instance = new T21Repository();
        T21RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T21RepositoryFolders.FilesDropboxPersonalMicrosoftEAppFolder _filesdropboxpersonalmicrosofte;
        T21RepositoryFolders.SearchResultsDropboxPersonalMiAppFolder _searchresultsdropboxpersonalmi;

        /// <summary>
        /// Gets the singleton class instance representing the T21Repository element repository.
        /// </summary>
        [RepositoryFolder("c2bec75b-a956-4d53-aebd-693bb95c3de4")]
        public static T21Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T21Repository() 
            : base("T21Repository", "/", null, 0, false, "c2bec75b-a956-4d53-aebd-693bb95c3de4", ".\\RepositoryImages\\T21Repositoryc2bec75b.rximgres")
        {
            _applicationundertest = new T21RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _filesdropboxpersonalmicrosofte = new T21RepositoryFolders.FilesDropboxPersonalMicrosoftEAppFolder(this);
            _searchresultsdropboxpersonalmi = new T21RepositoryFolders.SearchResultsDropboxPersonalMiAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c2bec75b-a956-4d53-aebd-693bb95c3de4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("55cf15f9-47cc-4355-862f-9bba0ec14fca")]
        public virtual T21RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The FilesDropboxPersonalMicrosoftE folder.
        /// </summary>
        [RepositoryFolder("e98b41e2-32f2-4cde-b91f-a71839850474")]
        public virtual T21RepositoryFolders.FilesDropboxPersonalMicrosoftEAppFolder FilesDropboxPersonalMicrosoftE
        {
            get { return _filesdropboxpersonalmicrosofte; }
        }

        /// <summary>
        /// The SearchResultsDropboxPersonalMi folder.
        /// </summary>
        [RepositoryFolder("f7b46108-9522-4a70-8be4-eabd311ca43b")]
        public virtual T21RepositoryFolders.SearchResultsDropboxPersonalMiAppFolder SearchResultsDropboxPersonalMi
        {
            get { return _searchresultsdropboxpersonalmi; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T21RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("55cf15f9-47cc-4355-862f-9bba0ec14fca")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "55cf15f9-47cc-4355-862f-9bba0ec14fca", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("55cf15f9-47cc-4355-862f-9bba0ec14fca")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("55cf15f9-47cc-4355-862f-9bba0ec14fca")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The FilesDropboxPersonalMicrosoftEAppFolder folder.
        /// </summary>
        [RepositoryFolder("e98b41e2-32f2-4cde-b91f-a71839850474")]
        public partial class FilesDropboxPersonalMicrosoftEAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _searchinfolderdropboxInfo;

            /// <summary>
            /// Creates a new FilesDropboxPersonalMicrosoftE  folder.
            /// </summary>
            public FilesDropboxPersonalMicrosoftEAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FilesDropboxPersonalMicrosoftE", "/form[@title>'Files - Dropbox - Personal']", parentFolder, 30000, null, true, "e98b41e2-32f2-4cde-b91f-a71839850474", "")
            {
                _searchinfolderdropboxInfo = new RepoItemInfo(this, "SearchInFolderDropbox", "container[@name>'Files - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']//container[@automationid>'']/text[@name='Files - Dropbox']/container[@classname='global-header--portaled']/container[@automationid='maestro-portal']/container[@automationid='global-header-portal']/container[@name='Global header']/container[@classname='_search-input-portal-web-redesign_kxyvl_8']//combobox[@name>'Search in folder “Dropbox']", ".//combobox[@name>'Search in folder “Dropbox']", 30000, null, "6fa6f01d-0b86-4de0-b4dc-c2b43f78f253");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e98b41e2-32f2-4cde-b91f-a71839850474")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e98b41e2-32f2-4cde-b91f-a71839850474")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SearchInFolderDropbox item.
            /// </summary>
            [RepositoryItem("6fa6f01d-0b86-4de0-b4dc-c2b43f78f253")]
            public virtual Ranorex.ComboBox SearchInFolderDropbox
            {
                get
                {
                    return _searchinfolderdropboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The SearchInFolderDropbox item info.
            /// </summary>
            [RepositoryItemInfo("6fa6f01d-0b86-4de0-b4dc-c2b43f78f253")]
            public virtual RepoItemInfo SearchInFolderDropboxInfo
            {
                get
                {
                    return _searchinfolderdropboxInfo;
                }
            }
        }

        /// <summary>
        /// The SearchResultsDropboxPersonalMiAppFolder folder.
        /// </summary>
        [RepositoryFolder("f7b46108-9522-4a70-8be4-eabd311ca43b")]
        public partial class SearchResultsDropboxPersonalMiAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _searchinfolderdropboxInfo;
            RepoItemInfo _noresultsfoundInfo;
            RepoItemInfo _text1resultInfo;

            /// <summary>
            /// Creates a new SearchResultsDropboxPersonalMi  folder.
            /// </summary>
            public SearchResultsDropboxPersonalMiAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SearchResultsDropboxPersonalMi", "/form[@title>'Search results - Dropbox -']", parentFolder, 30000, null, true, "f7b46108-9522-4a70-8be4-eabd311ca43b", "")
            {
                _searchinfolderdropboxInfo = new RepoItemInfo(this, "SearchInFolderDropbox", "container[@name>'Search results - Dropbox -']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']//container[@automationid>'']/text[@name='Search results - Dropbox']/container[@classname='global-header--portaled']/container[@automationid='maestro-portal']/container[@automationid='global-header-portal']/container[@name='Global header']/container[@classname='_search-input-portal-web-redesign_kxyvl_8']//combobox[@name>'Search in folder “Dropbox']", "", 30000, null, "58b3bd49-b773-4cc4-b062-a01e56898c80");
                _noresultsfoundInfo = new RepoItemInfo(this, "NoResultsFound", "container[@name>'Search results - Dropbox -']//container[@classname='SidebarContentsSplitView']//container[@automationid>'']/?/?/container[@classname='global-header--portaled']/container[@automationid='maestro-portal']/container[@automationid='maestro-content-portal']/?/?/container[@classname='_search-view-container-web-redesign-without-section-component_7vhv8_3']/container[@automationid='search-view']/text[@name='No results found']/text[@name='No results found']", "", 30000, null, "ebccf98c-3dd6-4610-9549-648ab0a242d8");
                _text1resultInfo = new RepoItemInfo(this, "Text1Result", "container[@name>'Search results - Dropbox -']//container[@classname='SidebarContentsSplitView']//container/text[@name='Search results - Dropbox']/container[@classname='global-header--portaled']/container[@automationid='maestro-portal']/container[@automationid='maestro-content-portal']/?/?/container[@classname='_search-view-container-web-redesign-without-section-component_7vhv8_3']/container[@classname='_search__view_7vhv8_65 maestro-content-scroll maestro-content-scroll_scroll-disabled _search__view-web-redesign_7vhv8_78']/table[@classname='mc-table brws-files-view-list']/?/?/element[@classname='mc-table-row mc-table-head-row']", ".//element[@classname='mc-table-row mc-table-head-row']", 30000, null, "44397fba-a90c-4be4-8706-f6e62c1d5918");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f7b46108-9522-4a70-8be4-eabd311ca43b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f7b46108-9522-4a70-8be4-eabd311ca43b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SearchInFolderDropbox item.
            /// </summary>
            [RepositoryItem("58b3bd49-b773-4cc4-b062-a01e56898c80")]
            public virtual Ranorex.ComboBox SearchInFolderDropbox
            {
                get
                {
                    return _searchinfolderdropboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The SearchInFolderDropbox item info.
            /// </summary>
            [RepositoryItemInfo("58b3bd49-b773-4cc4-b062-a01e56898c80")]
            public virtual RepoItemInfo SearchInFolderDropboxInfo
            {
                get
                {
                    return _searchinfolderdropboxInfo;
                }
            }

            /// <summary>
            /// The NoResultsFound item.
            /// </summary>
            [RepositoryItem("ebccf98c-3dd6-4610-9549-648ab0a242d8")]
            public virtual Ranorex.Text NoResultsFound
            {
                get
                {
                    return _noresultsfoundInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NoResultsFound item info.
            /// </summary>
            [RepositoryItemInfo("ebccf98c-3dd6-4610-9549-648ab0a242d8")]
            public virtual RepoItemInfo NoResultsFoundInfo
            {
                get
                {
                    return _noresultsfoundInfo;
                }
            }

            /// <summary>
            /// The Text1Result item.
            /// </summary>
            [RepositoryItem("44397fba-a90c-4be4-8706-f6e62c1d5918")]
            public virtual Ranorex.Unknown Text1Result
            {
                get
                {
                    return _text1resultInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Text1Result item info.
            /// </summary>
            [RepositoryItemInfo("44397fba-a90c-4be4-8706-f6e62c1d5918")]
            public virtual RepoItemInfo Text1ResultInfo
            {
                get
                {
                    return _text1resultInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
