///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T10
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T10Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("45b2e73f-0313-4394-a750-4ce471efb3fc")]
    public partial class T10Repository : RepoGenBaseFolder
    {
        static T10Repository instance = new T10Repository();
        T10RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T10RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder _logindropboxpersonalmicrosofte;

        /// <summary>
        /// Gets the singleton class instance representing the T10Repository element repository.
        /// </summary>
        [RepositoryFolder("45b2e73f-0313-4394-a750-4ce471efb3fc")]
        public static T10Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T10Repository() 
            : base("T10Repository", "/", null, 0, false, "45b2e73f-0313-4394-a750-4ce471efb3fc", ".\\RepositoryImages\\T10Repository45b2e73f.rximgres")
        {
            _applicationundertest = new T10RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _logindropboxpersonalmicrosofte = new T10RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("45b2e73f-0313-4394-a750-4ce471efb3fc")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("374d8898-a334-41b7-ab72-e9d3f71f05dc")]
        public virtual T10RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The LoginDropboxPersonalMicrosoftE folder.
        /// </summary>
        [RepositoryFolder("19d4104b-d10a-42d7-99c2-cb3346cecf4a")]
        public virtual T10RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder LoginDropboxPersonalMicrosoftE
        {
            get { return _logindropboxpersonalmicrosofte; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T10RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("374d8898-a334-41b7-ab72-e9d3f71f05dc")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "374d8898-a334-41b7-ab72-e9d3f71f05dc", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("374d8898-a334-41b7-ab72-e9d3f71f05dc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("374d8898-a334-41b7-ab72-e9d3f71f05dc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The LoginDropboxPersonalMicrosoftEAppFolder folder.
        /// </summary>
        [RepositoryFolder("19d4104b-d10a-42d7-99c2-cb3346cecf4a")]
        public partial class LoginDropboxPersonalMicrosoftEAppFolder : RepoGenBaseFolder
        {
            T10RepositoryFolders.SidebarContentsSplitViewFolder _sidebarcontentssplitview;

            /// <summary>
            /// Creates a new LoginDropboxPersonalMicrosoftE  folder.
            /// </summary>
            public LoginDropboxPersonalMicrosoftEAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginDropboxPersonalMicrosoftE", "/form[@title>'Login - Dropbox - Personal']", parentFolder, 30000, null, true, "19d4104b-d10a-42d7-99c2-cb3346cecf4a", "")
            {
                _sidebarcontentssplitview = new T10RepositoryFolders.SidebarContentsSplitViewFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("19d4104b-d10a-42d7-99c2-cb3346cecf4a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("19d4104b-d10a-42d7-99c2-cb3346cecf4a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SidebarContentsSplitView folder.
            /// </summary>
            [RepositoryFolder("0e0cbc04-901a-4d44-911a-892d9708dbbc")]
            public virtual T10RepositoryFolders.SidebarContentsSplitViewFolder SidebarContentsSplitView
            {
                get { return _sidebarcontentssplitview; }
            }
        }

        /// <summary>
        /// The SidebarContentsSplitViewFolder folder.
        /// </summary>
        [RepositoryFolder("0e0cbc04-901a-4d44-911a-892d9708dbbc")]
        public partial class SidebarContentsSplitViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pleaseenteranemailaddressInfo;
            RepoItemInfo _susiemail2141801686328677Info;
            RepoItemInfo _continueInfo;

            /// <summary>
            /// Creates a new SidebarContentsSplitView  folder.
            /// </summary>
            public SidebarContentsSplitViewFolder(RepoGenBaseFolder parentFolder) :
                    base("SidebarContentsSplitView", "container[@name>'Login - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']", parentFolder, 30000, null, false, "0e0cbc04-901a-4d44-911a-892d9708dbbc", "")
            {
                _pleaseenteranemailaddressInfo = new RepoItemInfo(this, "PleaseEnterAnEmailAddress", ".//container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//container/text[@name>'Please enter an email add']", "", 30000, null, "0c9d4c48-3097-4b8f-a870-d07fb3653b98");
                _susiemail2141801686328677Info = new RepoItemInfo(this, "SusiEmail2141801686328677", ".//container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//container[@classname='_field-input-wrapper_4srl7_50']/text[@automationid~'susi_email']", "", 30000, null, "0df5b162-8382-425b-a6c0-bca3ecb35e33");
                _continueInfo = new RepoItemInfo(this, "Continue", "container[@orientation='None' and @iscontentelement='True']/?/?/container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Continue']/?/?/text[@name='Continue']", "", 30000, null, "dc5b2ff2-61d5-465f-b972-597e850a9489");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0e0cbc04-901a-4d44-911a-892d9708dbbc")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0e0cbc04-901a-4d44-911a-892d9708dbbc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PleaseEnterAnEmailAddress item.
            /// </summary>
            [RepositoryItem("0c9d4c48-3097-4b8f-a870-d07fb3653b98")]
            public virtual Ranorex.Text PleaseEnterAnEmailAddress
            {
                get
                {
                    return _pleaseenteranemailaddressInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PleaseEnterAnEmailAddress item info.
            /// </summary>
            [RepositoryItemInfo("0c9d4c48-3097-4b8f-a870-d07fb3653b98")]
            public virtual RepoItemInfo PleaseEnterAnEmailAddressInfo
            {
                get
                {
                    return _pleaseenteranemailaddressInfo;
                }
            }

            /// <summary>
            /// The SusiEmail2141801686328677 item.
            /// </summary>
            [RepositoryItem("0df5b162-8382-425b-a6c0-bca3ecb35e33")]
            public virtual Ranorex.Text SusiEmail2141801686328677
            {
                get
                {
                    return _susiemail2141801686328677Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SusiEmail2141801686328677 item info.
            /// </summary>
            [RepositoryItemInfo("0df5b162-8382-425b-a6c0-bca3ecb35e33")]
            public virtual RepoItemInfo SusiEmail2141801686328677Info
            {
                get
                {
                    return _susiemail2141801686328677Info;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("dc5b2ff2-61d5-465f-b972-597e850a9489")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("dc5b2ff2-61d5-465f-b972-597e850a9489")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
