///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f4cdbe9e-1fa8-4678-a1c4-1d14695327c5")]
    public partial class T1Repository : RepoGenBaseFolder
    {
        static T1Repository instance = new T1Repository();
        T1RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T1RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder _registerdropboxpersonalmicrosof;

        /// <summary>
        /// Gets the singleton class instance representing the T1Repository element repository.
        /// </summary>
        [RepositoryFolder("f4cdbe9e-1fa8-4678-a1c4-1d14695327c5")]
        public static T1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T1Repository() 
            : base("T1Repository", "/", null, 0, false, "f4cdbe9e-1fa8-4678-a1c4-1d14695327c5", ".\\RepositoryImages\\T1Repositoryf4cdbe9e.rximgres")
        {
            _applicationundertest = new T1RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _registerdropboxpersonalmicrosof = new T1RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f4cdbe9e-1fa8-4678-a1c4-1d14695327c5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("c20253aa-3895-4fa4-8293-8e563f52710d")]
        public virtual T1RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosof folder.
        /// </summary>
        [RepositoryFolder("c09d9773-f258-4f87-9555-a139aad5e6fd")]
        public virtual T1RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder RegisterDropboxPersonalMicrosof
        {
            get { return _registerdropboxpersonalmicrosof; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T1RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("c20253aa-3895-4fa4-8293-8e563f52710d")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com/register']", parentFolder, 30000, null, false, "c20253aa-3895-4fa4-8293-8e563f52710d", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c20253aa-3895-4fa4-8293-8e563f52710d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c20253aa-3895-4fa4-8293-8e563f52710d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosofAppFolder folder.
        /// </summary>
        [RepositoryFolder("c09d9773-f258-4f87-9555-a139aad5e6fd")]
        public partial class RegisterDropboxPersonalMicrosofAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _continueInfo;
            RepoItemInfo _pleaseenteranemailaddressInfo;

            /// <summary>
            /// Creates a new RegisterDropboxPersonalMicrosof  folder.
            /// </summary>
            public RegisterDropboxPersonalMicrosofAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterDropboxPersonalMicrosof", "/form[@title>'Register - Dropbox - Personal']", parentFolder, 30000, null, true, "c09d9773-f258-4f87-9555-a139aad5e6fd", "")
            {
                _continueInfo = new RepoItemInfo(this, "Continue", "container[@name>'Register - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Continue']/?/?/text[@name='Continue']", "", 30000, null, "e7f52374-e50e-4720-842e-2c093a3fa6ee");
                _pleaseenteranemailaddressInfo = new RepoItemInfo(this, "PleaseEnterAnEmailAddress", "container[@name>'Register - Dropbox - Microsoft']//container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//container/text[@name>'Please enter an email add']", "", 30000, null, "16cb84a8-0e10-4f6f-8741-4422e758207d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c09d9773-f258-4f87-9555-a139aad5e6fd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c09d9773-f258-4f87-9555-a139aad5e6fd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("e7f52374-e50e-4720-842e-2c093a3fa6ee")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("e7f52374-e50e-4720-842e-2c093a3fa6ee")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The PleaseEnterAnEmailAddress item.
            /// </summary>
            [RepositoryItem("16cb84a8-0e10-4f6f-8741-4422e758207d")]
            public virtual Ranorex.Text PleaseEnterAnEmailAddress
            {
                get
                {
                    return _pleaseenteranemailaddressInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PleaseEnterAnEmailAddress item info.
            /// </summary>
            [RepositoryItemInfo("16cb84a8-0e10-4f6f-8741-4422e758207d")]
            public virtual RepoItemInfo PleaseEnterAnEmailAddressInfo
            {
                get
                {
                    return _pleaseenteranemailaddressInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
