///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6cbc1812-d83a-43af-8c6c-bb1ca5bfbb90")]
    public partial class MyTest1Repository : RepoGenBaseFolder
    {
        static MyTest1Repository instance = new MyTest1Repository();
        MyTest1RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder _logindropboxpersonalmicrosofte;
        MyTest1RepositoryFolders.FilesDropboxPersonalMicrosoftEAppFolder _filesdropboxpersonalmicrosofte;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("6cbc1812-d83a-43af-8c6c-bb1ca5bfbb90")]
        public static MyTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest1Repository() 
            : base("MyTest1Repository", "/", null, 0, false, "6cbc1812-d83a-43af-8c6c-bb1ca5bfbb90", ".\\RepositoryImages\\MyTest1Repository6cbc1812.rximgres")
        {
            _logindropboxpersonalmicrosofte = new MyTest1RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder(this);
            _filesdropboxpersonalmicrosofte = new MyTest1RepositoryFolders.FilesDropboxPersonalMicrosoftEAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6cbc1812-d83a-43af-8c6c-bb1ca5bfbb90")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LoginDropboxPersonalMicrosoftE folder.
        /// </summary>
        [RepositoryFolder("ddc1402b-1c96-4de0-8e55-5c0853da9243")]
        public virtual MyTest1RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder LoginDropboxPersonalMicrosoftE
        {
            get { return _logindropboxpersonalmicrosofte; }
        }

        /// <summary>
        /// The FilesDropboxPersonalMicrosoftE folder.
        /// </summary>
        [RepositoryFolder("32c515f3-0323-4e13-a824-9c5ba729c10c")]
        public virtual MyTest1RepositoryFolders.FilesDropboxPersonalMicrosoftEAppFolder FilesDropboxPersonalMicrosoftE
        {
            get { return _filesdropboxpersonalmicrosofte; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest1RepositoryFolders
    {
        /// <summary>
        /// The LoginDropboxPersonalMicrosoftEAppFolder folder.
        /// </summary>
        [RepositoryFolder("ddc1402b-1c96-4de0-8e55-5c0853da9243")]
        public partial class LoginDropboxPersonalMicrosoftEAppFolder : RepoGenBaseFolder
        {
            MyTest1RepositoryFolders.LoginOrRegisterPageContentFolder _loginorregisterpagecontent;
            RepoItemInfo _continueInfo;

            /// <summary>
            /// Creates a new LoginDropboxPersonalMicrosoftE  folder.
            /// </summary>
            public LoginDropboxPersonalMicrosoftEAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginDropboxPersonalMicrosoftE", "/form[@title>'Login - Dropbox - Personal']", parentFolder, 30000, null, true, "ddc1402b-1c96-4de0-8e55-5c0853da9243", "")
            {
                _loginorregisterpagecontent = new MyTest1RepositoryFolders.LoginOrRegisterPageContentFolder(this);
                _continueInfo = new RepoItemInfo(this, "Continue", "container[@name>'Login - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@orientation='None' and @iscontentelement='True']/?/?/?/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Continue']/?/?/text[@name='Continue']", ".//text[@name='Continue']", 30000, null, "7b8f5cdf-a318-4a6a-b6fb-0e499131b0d1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ddc1402b-1c96-4de0-8e55-5c0853da9243")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ddc1402b-1c96-4de0-8e55-5c0853da9243")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("7b8f5cdf-a318-4a6a-b6fb-0e499131b0d1")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("7b8f5cdf-a318-4a6a-b6fb-0e499131b0d1")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The LoginOrRegisterPageContent folder.
            /// </summary>
            [RepositoryFolder("88bb056d-e486-4b39-8577-185f0cbe7274")]
            public virtual MyTest1RepositoryFolders.LoginOrRegisterPageContentFolder LoginOrRegisterPageContent
            {
                get { return _loginorregisterpagecontent; }
            }
        }

        /// <summary>
        /// The LoginOrRegisterPageContentFolder folder.
        /// </summary>
        [RepositoryFolder("88bb056d-e486-4b39-8577-185f0cbe7274")]
        public partial class LoginOrRegisterPageContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginInfo;
            RepoItemInfo _rememberme03138055497110104Info;
            RepoItemInfo _loginpassword6545782404941085Info;
            RepoItemInfo _susiemail9930172465765765Info;

            /// <summary>
            /// Creates a new LoginOrRegisterPageContent  folder.
            /// </summary>
            public LoginOrRegisterPageContentFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginOrRegisterPageContent", "container[@name>'Login - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']//?/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']/container[@classname='susi-wrapper']", parentFolder, 30000, null, false, "88bb056d-e486-4b39-8577-185f0cbe7274", "")
            {
                _loginInfo = new RepoItemInfo(this, "LogIn", ".//button[@name='Log in']/?/?/text[@name='Log in']", "", 30000, null, "e38ae336-4d61-430e-83d7-c765f0d184ee");
                _rememberme03138055497110104Info = new RepoItemInfo(this, "RememberMe03138055497110104", ".//checkbox[@automationid~'remember_me']", "", 30000, null, "e778fff7-6a98-42e3-b540-808979c2411a");
                _loginpassword6545782404941085Info = new RepoItemInfo(this, "LoginPassword6545782404941085", ".//container[@classname='_field-input-wrapper_4srl7_50']/text[@automationid~'login_password']", "", 30000, null, "7dd5186b-6257-484b-913c-92fc5a1daaa4");
                _susiemail9930172465765765Info = new RepoItemInfo(this, "SusiEmail9930172465765765", ".//container[@classname='_field-input-wrapper_4srl7_50']/text[@automationid~'susi_email']", "", 30000, null, "f3202d3c-a965-4001-b8db-c189c68e9227");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("88bb056d-e486-4b39-8577-185f0cbe7274")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("88bb056d-e486-4b39-8577-185f0cbe7274")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("e38ae336-4d61-430e-83d7-c765f0d184ee")]
            public virtual Ranorex.Text LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("e38ae336-4d61-430e-83d7-c765f0d184ee")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The RememberMe03138055497110104 item.
            /// </summary>
            [RepositoryItem("e778fff7-6a98-42e3-b540-808979c2411a")]
            public virtual Ranorex.CheckBox RememberMe03138055497110104
            {
                get
                {
                    return _rememberme03138055497110104Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The RememberMe03138055497110104 item info.
            /// </summary>
            [RepositoryItemInfo("e778fff7-6a98-42e3-b540-808979c2411a")]
            public virtual RepoItemInfo RememberMe03138055497110104Info
            {
                get
                {
                    return _rememberme03138055497110104Info;
                }
            }

            /// <summary>
            /// The LoginPassword6545782404941085 item.
            /// </summary>
            [RepositoryItem("7dd5186b-6257-484b-913c-92fc5a1daaa4")]
            public virtual Ranorex.Text LoginPassword6545782404941085
            {
                get
                {
                    return _loginpassword6545782404941085Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LoginPassword6545782404941085 item info.
            /// </summary>
            [RepositoryItemInfo("7dd5186b-6257-484b-913c-92fc5a1daaa4")]
            public virtual RepoItemInfo LoginPassword6545782404941085Info
            {
                get
                {
                    return _loginpassword6545782404941085Info;
                }
            }

            /// <summary>
            /// The SusiEmail9930172465765765 item.
            /// </summary>
            [RepositoryItem("f3202d3c-a965-4001-b8db-c189c68e9227")]
            public virtual Ranorex.Text SusiEmail9930172465765765
            {
                get
                {
                    return _susiemail9930172465765765Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SusiEmail9930172465765765 item info.
            /// </summary>
            [RepositoryItemInfo("f3202d3c-a965-4001-b8db-c189c68e9227")]
            public virtual RepoItemInfo SusiEmail9930172465765765Info
            {
                get
                {
                    return _susiemail9930172465765765Info;
                }
            }
        }

        /// <summary>
        /// The FilesDropboxPersonalMicrosoftEAppFolder folder.
        /// </summary>
        [RepositoryFolder("32c515f3-0323-4e13-a824-9c5ba729c10c")]
        public partial class FilesDropboxPersonalMicrosoftEAppFolder : RepoGenBaseFolder
        {
            MyTest1RepositoryFolders.SidebarContentsSplitViewFolder _sidebarcontentssplitview;

            /// <summary>
            /// Creates a new FilesDropboxPersonalMicrosoftE  folder.
            /// </summary>
            public FilesDropboxPersonalMicrosoftEAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FilesDropboxPersonalMicrosoftE", "/form[@title>'Files - Dropbox - Personal']", parentFolder, 30000, null, true, "32c515f3-0323-4e13-a824-9c5ba729c10c", "")
            {
                _sidebarcontentssplitview = new MyTest1RepositoryFolders.SidebarContentsSplitViewFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("32c515f3-0323-4e13-a824-9c5ba729c10c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("32c515f3-0323-4e13-a824-9c5ba729c10c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SidebarContentsSplitView folder.
            /// </summary>
            [RepositoryFolder("1ae9b1d7-dd3e-48b8-8f49-78776b8ca784")]
            public virtual MyTest1RepositoryFolders.SidebarContentsSplitViewFolder SidebarContentsSplitView
            {
                get { return _sidebarcontentssplitview; }
            }
        }

        /// <summary>
        /// The SidebarContentsSplitViewFolder folder.
        /// </summary>
        [RepositoryFolder("1ae9b1d7-dd3e-48b8-8f49-78776b8ca784")]
        public partial class SidebarContentsSplitViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _accountmenuInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _minhnguyễnInfo;

            /// <summary>
            /// Creates a new SidebarContentsSplitView  folder.
            /// </summary>
            public SidebarContentsSplitViewFolder(RepoGenBaseFolder parentFolder) :
                    base("SidebarContentsSplitView", "container[@name>'Files - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']", parentFolder, 30000, null, false, "1ae9b1d7-dd3e-48b8-8f49-78776b8ca784", "")
            {
                _accountmenuInfo = new RepoItemInfo(this, "AccountMenu", "container[@classname='SidebarContentsSplitView']//container/text[@name='Files - Dropbox']/container[@classname='global-header--portaled']/container[@automationid='maestro-portal']/container[@automationid='global-header-portal']/container[@name='Global header']//button[@name='Account menu']", "", 30000, null, "4e8ecc41-33eb-486e-8d1b-ea2fbdffdd53");
                _logoutInfo = new RepoItemInfo(this, "LogOut", "container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//?/text[@name='Files - Dropbox']/container[@classname='global-header--portaled']/container[@classname='dig-Layer']//menuitem[@name='Log out']//text[@name='Log out']", "", 30000, null, "985fb100-1eef-498b-a075-ffba66684d31");
                _minhnguyễnInfo = new RepoItemInfo(this, "MinhNguyễn", "container[@classname='SidebarContentsSplitView']/?/?/container[@classname='SidebarContentsSplitView']//?/text[@name='Files - Dropbox']/container[@classname='global-header--portaled']/container[@classname='dig-Layer']//text[@name='Minh Nguyễn']", "", 30000, null, "b0f55d95-a4bc-4837-a7ff-1c9b3427b83c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1ae9b1d7-dd3e-48b8-8f49-78776b8ca784")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1ae9b1d7-dd3e-48b8-8f49-78776b8ca784")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AccountMenu item.
            /// </summary>
            [RepositoryItem("4e8ecc41-33eb-486e-8d1b-ea2fbdffdd53")]
            public virtual Ranorex.Button AccountMenu
            {
                get
                {
                    return _accountmenuInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AccountMenu item info.
            /// </summary>
            [RepositoryItemInfo("4e8ecc41-33eb-486e-8d1b-ea2fbdffdd53")]
            public virtual RepoItemInfo AccountMenuInfo
            {
                get
                {
                    return _accountmenuInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("985fb100-1eef-498b-a075-ffba66684d31")]
            public virtual Ranorex.Text LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("985fb100-1eef-498b-a075-ffba66684d31")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The MinhNguyễn item.
            /// </summary>
            [RepositoryItem("b0f55d95-a4bc-4837-a7ff-1c9b3427b83c")]
            public virtual Ranorex.Text MinhNguyễn
            {
                get
                {
                    return _minhnguyễnInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MinhNguyễn item info.
            /// </summary>
            [RepositoryItemInfo("b0f55d95-a4bc-4837-a7ff-1c9b3427b83c")]
            public virtual RepoItemInfo MinhNguyễnInfo
            {
                get
                {
                    return _minhnguyễnInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
