///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Password recording.
    /// </summary>
    [TestModule("dbc92e6b-1cbe-4feb-9468-17432e97e9ce", ModuleType.Recording, 1)]
    public partial class Password : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1Repository repository.
        /// </summary>
        public static MyTest1Repository repo = MyTest1Repository.Instance;

        static Password instance = new Password();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Password()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Password Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginDropboxPersonalMicrosoftE.Continue' at 42;15.", repo.LoginDropboxPersonalMicrosoftE.ContinueInfo, new RecordItemIndex(0));
            repo.LoginDropboxPersonalMicrosoftE.Continue.Click("42;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginDropboxPersonalMicrosoftE.LoginOrRegisterPageContent.LoginPassword6545782404941085' at 49;32.", repo.LoginDropboxPersonalMicrosoftE.LoginOrRegisterPageContent.LoginPassword6545782404941085Info, new RecordItemIndex(1));
            repo.LoginDropboxPersonalMicrosoftE.LoginOrRegisterPageContent.LoginPassword6545782404941085.Click("49;32");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Minh@2k3' with focus on 'LoginDropboxPersonalMicrosoftE.LoginOrRegisterPageContent.LoginPassword6545782404941085'.", repo.LoginDropboxPersonalMicrosoftE.LoginOrRegisterPageContent.LoginPassword6545782404941085Info, new RecordItemIndex(2));
            repo.LoginDropboxPersonalMicrosoftE.LoginOrRegisterPageContent.LoginPassword6545782404941085.PressKeys("Minh@2k3");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
