///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateAccount recording.
    /// </summary>
    [TestModule("6b2516c5-846e-4413-a6f9-9b335563b50d", ModuleType.Recording, 1)]
    public partial class ValidateAccount : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1Repository repository.
        /// </summary>
        public static MyTest1Repository repo = MyTest1Repository.Instance;

        static ValidateAccount instance = new ValidateAccount();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateAccount()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateAccount Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.AccountMenu' at 12;21.", repo.FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.AccountMenuInfo, new RecordItemIndex(0));
            repo.FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.AccountMenu.Click("12;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Minh Nguyễn') on item 'FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.MinhNguyễn'.", repo.FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.MinhNguyễnInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.FilesDropboxPersonalMicrosoftE.SidebarContentsSplitView.MinhNguyễnInfo, "Text", "Minh Nguyễn");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
