///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test13
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test13Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("779d0d2b-cdad-4d24-b129-470d0d97ab83")]
    public partial class Test13Repository : RepoGenBaseFolder
    {
        static Test13Repository instance = new Test13Repository();
        Test13RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Test13RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder _logindropboxpersonalmicrosofte;

        /// <summary>
        /// Gets the singleton class instance representing the Test13Repository element repository.
        /// </summary>
        [RepositoryFolder("779d0d2b-cdad-4d24-b129-470d0d97ab83")]
        public static Test13Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test13Repository() 
            : base("Test13Repository", "/", null, 0, false, "779d0d2b-cdad-4d24-b129-470d0d97ab83", ".\\RepositoryImages\\Test13Repository779d0d2b.rximgres")
        {
            _applicationundertest = new Test13RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _logindropboxpersonalmicrosofte = new Test13RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("779d0d2b-cdad-4d24-b129-470d0d97ab83")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("8e964805-875c-44ad-a576-b5a21202090b")]
        public virtual Test13RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The LoginDropboxPersonalMicrosoftE folder.
        /// </summary>
        [RepositoryFolder("0b09c344-b979-40b6-92f1-b3e4ac1e7be8")]
        public virtual Test13RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder LoginDropboxPersonalMicrosoftE
        {
            get { return _logindropboxpersonalmicrosofte; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Test13RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("8e964805-875c-44ad-a576-b5a21202090b")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "8e964805-875c-44ad-a576-b5a21202090b", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8e964805-875c-44ad-a576-b5a21202090b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8e964805-875c-44ad-a576-b5a21202090b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The LoginDropboxPersonalMicrosoftEAppFolder folder.
        /// </summary>
        [RepositoryFolder("0b09c344-b979-40b6-92f1-b3e4ac1e7be8")]
        public partial class LoginDropboxPersonalMicrosoftEAppFolder : RepoGenBaseFolder
        {
            Test13RepositoryFolders.SidebarContentsSplitViewFolder _sidebarcontentssplitview;

            /// <summary>
            /// Creates a new LoginDropboxPersonalMicrosoftE  folder.
            /// </summary>
            public LoginDropboxPersonalMicrosoftEAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginDropboxPersonalMicrosoftE", "/form[@title>'Login - Dropbox - Personal']", parentFolder, 30000, null, true, "0b09c344-b979-40b6-92f1-b3e4ac1e7be8", "")
            {
                _sidebarcontentssplitview = new Test13RepositoryFolders.SidebarContentsSplitViewFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0b09c344-b979-40b6-92f1-b3e4ac1e7be8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0b09c344-b979-40b6-92f1-b3e4ac1e7be8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SidebarContentsSplitView folder.
            /// </summary>
            [RepositoryFolder("2572d474-20ec-4930-a808-d27f2c59e603")]
            public virtual Test13RepositoryFolders.SidebarContentsSplitViewFolder SidebarContentsSplitView
            {
                get { return _sidebarcontentssplitview; }
            }
        }

        /// <summary>
        /// The SidebarContentsSplitViewFolder folder.
        /// </summary>
        [RepositoryFolder("2572d474-20ec-4930-a808-d27f2c59e603")]
        public partial class SidebarContentsSplitViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _susiemail6693943736291585Info;
            RepoItemInfo _continueInfo;
            RepoItemInfo _welcomebackInfo;

            /// <summary>
            /// Creates a new SidebarContentsSplitView  folder.
            /// </summary>
            public SidebarContentsSplitViewFolder(RepoGenBaseFolder parentFolder) :
                    base("SidebarContentsSplitView", "container[@name>'Login - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']", parentFolder, 30000, null, false, "2572d474-20ec-4930-a808-d27f2c59e603", "")
            {
                _susiemail6693943736291585Info = new RepoItemInfo(this, "SusiEmail6693943736291585", "container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//container[@classname='_field-input-wrapper_4srl7_50']/text[@automationid~'susi_email']", "", 30000, null, "6103d0ab-c13c-4a4b-a799-b19e05af30c4");
                _continueInfo = new RepoItemInfo(this, "Continue", "container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@orientation='None' and @iscontentelement='True']/?/?/container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Continue']/?/?/text[@name='Continue']", "", 30000, null, "fd6e10ea-c53a-42a6-a11c-632b14015b50");
                _welcomebackInfo = new RepoItemInfo(this, "WelcomeBack", "container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//text[@name='Welcome back']", "", 30000, null, "adbf92cb-3993-46e6-99a3-04b4c1b7ab5c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2572d474-20ec-4930-a808-d27f2c59e603")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2572d474-20ec-4930-a808-d27f2c59e603")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SusiEmail6693943736291585 item.
            /// </summary>
            [RepositoryItem("6103d0ab-c13c-4a4b-a799-b19e05af30c4")]
            public virtual Ranorex.Text SusiEmail6693943736291585
            {
                get
                {
                    return _susiemail6693943736291585Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SusiEmail6693943736291585 item info.
            /// </summary>
            [RepositoryItemInfo("6103d0ab-c13c-4a4b-a799-b19e05af30c4")]
            public virtual RepoItemInfo SusiEmail6693943736291585Info
            {
                get
                {
                    return _susiemail6693943736291585Info;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("fd6e10ea-c53a-42a6-a11c-632b14015b50")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("fd6e10ea-c53a-42a6-a11c-632b14015b50")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The WelcomeBack item.
            /// </summary>
            [RepositoryItem("adbf92cb-3993-46e6-99a3-04b4c1b7ab5c")]
            public virtual Ranorex.Text WelcomeBack
            {
                get
                {
                    return _welcomebackInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The WelcomeBack item info.
            /// </summary>
            [RepositoryItemInfo("adbf92cb-3993-46e6-99a3-04b4c1b7ab5c")]
            public virtual RepoItemInfo WelcomeBackInfo
            {
                get
                {
                    return _welcomebackInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
