///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace T15
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EmailDoesntExists recording.
    /// </summary>
    [TestModule("77d49b9a-c506-4232-b375-98464d4c4279", ModuleType.Recording, 1)]
    public partial class EmailDoesntExists : ITestModule
    {
        /// <summary>
        /// Holds an instance of the T15Repository repository.
        /// </summary>
        public static T15Repository repo = T15Repository.Instance;

        static EmailDoesntExists instance = new EmailDoesntExists();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EmailDoesntExists()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EmailDoesntExists Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SusiEmail19781152614504882' at 142;26.", repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SusiEmail19781152614504882Info, new RecordItemIndex(0));
            repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SusiEmail19781152614504882.Click("142;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aduconchoxuytbg@gmail.com' with focus on 'LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SusiEmail19781152614504882'.", repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SusiEmail19781152614504882Info, new RecordItemIndex(1));
            repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SusiEmail19781152614504882.PressKeys("aduconchoxuytbg@gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.Continue' at 27;14.", repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.ContinueInfo, new RecordItemIndex(2));
            repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.Continue.Click("27;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Sign up for free') on item 'LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SignUpForFree'.", repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SignUpForFreeInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.LoginDropboxPersonalMicrosoftE.SidebarContentsSplitView.SignUpForFreeInfo, "Text", "Sign up for free");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
