///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T15
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T15Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("7cbe8f53-c4fd-473d-b71b-f28cb0c2d093")]
    public partial class T15Repository : RepoGenBaseFolder
    {
        static T15Repository instance = new T15Repository();
        T15RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T15RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder _logindropboxpersonalmicrosofte;

        /// <summary>
        /// Gets the singleton class instance representing the T15Repository element repository.
        /// </summary>
        [RepositoryFolder("7cbe8f53-c4fd-473d-b71b-f28cb0c2d093")]
        public static T15Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T15Repository() 
            : base("T15Repository", "/", null, 0, false, "7cbe8f53-c4fd-473d-b71b-f28cb0c2d093", ".\\RepositoryImages\\T15Repository7cbe8f53.rximgres")
        {
            _applicationundertest = new T15RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _logindropboxpersonalmicrosofte = new T15RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7cbe8f53-c4fd-473d-b71b-f28cb0c2d093")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("9af8ae83-b14a-482d-9a69-96e250bfdbb0")]
        public virtual T15RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The LoginDropboxPersonalMicrosoftE folder.
        /// </summary>
        [RepositoryFolder("2576f686-ffe4-4946-bfed-bb819a2c9de4")]
        public virtual T15RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder LoginDropboxPersonalMicrosoftE
        {
            get { return _logindropboxpersonalmicrosofte; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T15RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("9af8ae83-b14a-482d-9a69-96e250bfdbb0")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "9af8ae83-b14a-482d-9a69-96e250bfdbb0", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9af8ae83-b14a-482d-9a69-96e250bfdbb0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9af8ae83-b14a-482d-9a69-96e250bfdbb0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The LoginDropboxPersonalMicrosoftEAppFolder folder.
        /// </summary>
        [RepositoryFolder("2576f686-ffe4-4946-bfed-bb819a2c9de4")]
        public partial class LoginDropboxPersonalMicrosoftEAppFolder : RepoGenBaseFolder
        {
            T15RepositoryFolders.SidebarContentsSplitViewFolder _sidebarcontentssplitview;

            /// <summary>
            /// Creates a new LoginDropboxPersonalMicrosoftE  folder.
            /// </summary>
            public LoginDropboxPersonalMicrosoftEAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginDropboxPersonalMicrosoftE", "/form[@title>'Login - Dropbox - Personal']", parentFolder, 30000, null, true, "2576f686-ffe4-4946-bfed-bb819a2c9de4", "")
            {
                _sidebarcontentssplitview = new T15RepositoryFolders.SidebarContentsSplitViewFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2576f686-ffe4-4946-bfed-bb819a2c9de4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2576f686-ffe4-4946-bfed-bb819a2c9de4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SidebarContentsSplitView folder.
            /// </summary>
            [RepositoryFolder("312d5d91-8f59-4c20-b057-dea1c20b880a")]
            public virtual T15RepositoryFolders.SidebarContentsSplitViewFolder SidebarContentsSplitView
            {
                get { return _sidebarcontentssplitview; }
            }
        }

        /// <summary>
        /// The SidebarContentsSplitViewFolder folder.
        /// </summary>
        [RepositoryFolder("312d5d91-8f59-4c20-b057-dea1c20b880a")]
        public partial class SidebarContentsSplitViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _susiemail19781152614504882Info;
            RepoItemInfo _signupforfreeInfo;
            RepoItemInfo _continueInfo;

            /// <summary>
            /// Creates a new SidebarContentsSplitView  folder.
            /// </summary>
            public SidebarContentsSplitViewFolder(RepoGenBaseFolder parentFolder) :
                    base("SidebarContentsSplitView", "container[@name>'Login - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']", parentFolder, 30000, null, false, "312d5d91-8f59-4c20-b057-dea1c20b880a", "")
            {
                _susiemail19781152614504882Info = new RepoItemInfo(this, "SusiEmail19781152614504882", ".//container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//container[@classname='_field-input-wrapper_4srl7_50']/text[@automationid~'susi_email']", "", 30000, null, "42201ebe-cefd-4011-86da-3b822468606a");
                _signupforfreeInfo = new RepoItemInfo(this, "SignUpForFree", ".//container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//text[@name='Sign up for free']", "", 30000, null, "99d5041d-fbfe-4e2d-814e-a17182502f40");
                _continueInfo = new RepoItemInfo(this, "Continue", "container[@classname='SplitWindowContainerView']/?/?/container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Continue']/?/?/text[@name='Continue']", "", 30000, null, "26c729ba-ce5c-42d7-93f2-e3dd5f437125");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("312d5d91-8f59-4c20-b057-dea1c20b880a")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("312d5d91-8f59-4c20-b057-dea1c20b880a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SusiEmail19781152614504882 item.
            /// </summary>
            [RepositoryItem("42201ebe-cefd-4011-86da-3b822468606a")]
            public virtual Ranorex.Text SusiEmail19781152614504882
            {
                get
                {
                    return _susiemail19781152614504882Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SusiEmail19781152614504882 item info.
            /// </summary>
            [RepositoryItemInfo("42201ebe-cefd-4011-86da-3b822468606a")]
            public virtual RepoItemInfo SusiEmail19781152614504882Info
            {
                get
                {
                    return _susiemail19781152614504882Info;
                }
            }

            /// <summary>
            /// The SignUpForFree item.
            /// </summary>
            [RepositoryItem("99d5041d-fbfe-4e2d-814e-a17182502f40")]
            public virtual Ranorex.Text SignUpForFree
            {
                get
                {
                    return _signupforfreeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SignUpForFree item info.
            /// </summary>
            [RepositoryItemInfo("99d5041d-fbfe-4e2d-814e-a17182502f40")]
            public virtual RepoItemInfo SignUpForFreeInfo
            {
                get
                {
                    return _signupforfreeInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("26c729ba-ce5c-42d7-93f2-e3dd5f437125")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("26c729ba-ce5c-42d7-93f2-e3dd5f437125")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
