///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T5
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T5Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("8bb4789e-5161-42ac-99c1-e7d897074afe")]
    public partial class T5Repository : RepoGenBaseFolder
    {
        static T5Repository instance = new T5Repository();
        T5RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T5RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder _registerdropboxpersonalmicrosof;

        /// <summary>
        /// Gets the singleton class instance representing the T5Repository element repository.
        /// </summary>
        [RepositoryFolder("8bb4789e-5161-42ac-99c1-e7d897074afe")]
        public static T5Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T5Repository() 
            : base("T5Repository", "/", null, 0, false, "8bb4789e-5161-42ac-99c1-e7d897074afe", ".\\RepositoryImages\\T5Repository8bb4789e.rximgres")
        {
            _applicationundertest = new T5RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _registerdropboxpersonalmicrosof = new T5RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8bb4789e-5161-42ac-99c1-e7d897074afe")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("6961a2ec-e573-49ec-97b8-2e89f1487065")]
        public virtual T5RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosof folder.
        /// </summary>
        [RepositoryFolder("26493698-41a8-40f7-9004-c44086d33575")]
        public virtual T5RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder RegisterDropboxPersonalMicrosof
        {
            get { return _registerdropboxpersonalmicrosof; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T5RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("6961a2ec-e573-49ec-97b8-2e89f1487065")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "6961a2ec-e573-49ec-97b8-2e89f1487065", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6961a2ec-e573-49ec-97b8-2e89f1487065")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6961a2ec-e573-49ec-97b8-2e89f1487065")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosofAppFolder folder.
        /// </summary>
        [RepositoryFolder("26493698-41a8-40f7-9004-c44086d33575")]
        public partial class RegisterDropboxPersonalMicrosofAppFolder : RepoGenBaseFolder
        {
            T5RepositoryFolders.SidebarContentsSplitViewFolder _sidebarcontentssplitview;

            /// <summary>
            /// Creates a new RegisterDropboxPersonalMicrosof  folder.
            /// </summary>
            public RegisterDropboxPersonalMicrosofAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterDropboxPersonalMicrosof", "/form[@title>'Register - Dropbox - Personal']", parentFolder, 30000, null, true, "26493698-41a8-40f7-9004-c44086d33575", "")
            {
                _sidebarcontentssplitview = new T5RepositoryFolders.SidebarContentsSplitViewFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("26493698-41a8-40f7-9004-c44086d33575")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("26493698-41a8-40f7-9004-c44086d33575")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SidebarContentsSplitView folder.
            /// </summary>
            [RepositoryFolder("3e02d226-b72f-433f-893a-12cf697ee731")]
            public virtual T5RepositoryFolders.SidebarContentsSplitViewFolder SidebarContentsSplitView
            {
                get { return _sidebarcontentssplitview; }
            }
        }

        /// <summary>
        /// The SidebarContentsSplitViewFolder folder.
        /// </summary>
        [RepositoryFolder("3e02d226-b72f-433f-893a-12cf697ee731")]
        public partial class SidebarContentsSplitViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginorregisterpagecontentInfo;
            RepoItemInfo _welcomebackInfo;
            RepoItemInfo _continueInfo;
            RepoItemInfo _susiemail7418162861018489Info;

            /// <summary>
            /// Creates a new SidebarContentsSplitView  folder.
            /// </summary>
            public SidebarContentsSplitViewFolder(RepoGenBaseFolder parentFolder) :
                    base("SidebarContentsSplitView", "container[@name>'Register - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']", parentFolder, 30000, null, false, "3e02d226-b72f-433f-893a-12cf697ee731", "")
            {
                _loginorregisterpagecontentInfo = new RepoItemInfo(this, "LoginOrRegisterPageContent", ".//container[@automationid='36837728']/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']", "", 30000, null, "7d5ad733-1592-4380-8d77-4d510083b5f9");
                _welcomebackInfo = new RepoItemInfo(this, "WelcomeBack", ".//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']/?/?/text[@name='Welcome back']", "", 30000, null, "0dabc951-75bb-474a-9874-f9630a08bbe4");
                _continueInfo = new RepoItemInfo(this, "Continue", "container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Continue']/?/?/text[@name='Continue']", "", 30000, null, "6ab4b416-7ab6-482c-ad9f-ff640904d544");
                _susiemail7418162861018489Info = new RepoItemInfo(this, "SusiEmail7418162861018489", "container[@classname='SidebarContentsSplitView']/?/?/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//text[@automationid~'susi_email']", "", 30000, null, "e6ed3eed-0c09-470d-8fb1-22e3c18a1a16");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3e02d226-b72f-433f-893a-12cf697ee731")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3e02d226-b72f-433f-893a-12cf697ee731")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginOrRegisterPageContent item.
            /// </summary>
            [RepositoryItem("7d5ad733-1592-4380-8d77-4d510083b5f9")]
            public virtual Ranorex.Container LoginOrRegisterPageContent
            {
                get
                {
                    return _loginorregisterpagecontentInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The LoginOrRegisterPageContent item info.
            /// </summary>
            [RepositoryItemInfo("7d5ad733-1592-4380-8d77-4d510083b5f9")]
            public virtual RepoItemInfo LoginOrRegisterPageContentInfo
            {
                get
                {
                    return _loginorregisterpagecontentInfo;
                }
            }

            /// <summary>
            /// The WelcomeBack item.
            /// </summary>
            [RepositoryItem("0dabc951-75bb-474a-9874-f9630a08bbe4")]
            public virtual Ranorex.Text WelcomeBack
            {
                get
                {
                    return _welcomebackInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The WelcomeBack item info.
            /// </summary>
            [RepositoryItemInfo("0dabc951-75bb-474a-9874-f9630a08bbe4")]
            public virtual RepoItemInfo WelcomeBackInfo
            {
                get
                {
                    return _welcomebackInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("6ab4b416-7ab6-482c-ad9f-ff640904d544")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("6ab4b416-7ab6-482c-ad9f-ff640904d544")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The SusiEmail7418162861018489 item.
            /// </summary>
            [RepositoryItem("e6ed3eed-0c09-470d-8fb1-22e3c18a1a16")]
            public virtual Ranorex.Text SusiEmail7418162861018489
            {
                get
                {
                    return _susiemail7418162861018489Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SusiEmail7418162861018489 item info.
            /// </summary>
            [RepositoryItemInfo("e6ed3eed-0c09-470d-8fb1-22e3c18a1a16")]
            public virtual RepoItemInfo SusiEmail7418162861018489Info
            {
                get
                {
                    return _susiemail7418162861018489Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
