///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T8
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T8Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e8803486-3e8b-484f-a430-7365883beabf")]
    public partial class T8Repository : RepoGenBaseFolder
    {
        static T8Repository instance = new T8Repository();
        T8RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T8RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder _registerdropboxpersonalmicrosof;

        /// <summary>
        /// Gets the singleton class instance representing the T8Repository element repository.
        /// </summary>
        [RepositoryFolder("e8803486-3e8b-484f-a430-7365883beabf")]
        public static T8Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T8Repository() 
            : base("T8Repository", "/", null, 0, false, "e8803486-3e8b-484f-a430-7365883beabf", ".\\RepositoryImages\\T8Repositorye8803486.rximgres")
        {
            _applicationundertest = new T8RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _registerdropboxpersonalmicrosof = new T8RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e8803486-3e8b-484f-a430-7365883beabf")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("942ba1ec-8ef1-497b-a222-185d28c72c6b")]
        public virtual T8RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosof folder.
        /// </summary>
        [RepositoryFolder("e0ab6d58-6f99-4ec9-837f-8ef8a45824e9")]
        public virtual T8RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder RegisterDropboxPersonalMicrosof
        {
            get { return _registerdropboxpersonalmicrosof; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T8RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("942ba1ec-8ef1-497b-a222-185d28c72c6b")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "942ba1ec-8ef1-497b-a222-185d28c72c6b", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("942ba1ec-8ef1-497b-a222-185d28c72c6b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("942ba1ec-8ef1-497b-a222-185d28c72c6b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosofAppFolder folder.
        /// </summary>
        [RepositoryFolder("e0ab6d58-6f99-4ec9-837f-8ef8a45824e9")]
        public partial class RegisterDropboxPersonalMicrosofAppFolder : RepoGenBaseFolder
        {
            T8RepositoryFolders.SidebarContentsSplitViewFolder _sidebarcontentssplitview;

            /// <summary>
            /// Creates a new RegisterDropboxPersonalMicrosof  folder.
            /// </summary>
            public RegisterDropboxPersonalMicrosofAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterDropboxPersonalMicrosof", "/form[@title>'Register - Dropbox - Personal']", parentFolder, 30000, null, true, "e0ab6d58-6f99-4ec9-837f-8ef8a45824e9", "")
            {
                _sidebarcontentssplitview = new T8RepositoryFolders.SidebarContentsSplitViewFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e0ab6d58-6f99-4ec9-837f-8ef8a45824e9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e0ab6d58-6f99-4ec9-837f-8ef8a45824e9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SidebarContentsSplitView folder.
            /// </summary>
            [RepositoryFolder("37455347-449a-442d-844b-cef16039fa54")]
            public virtual T8RepositoryFolders.SidebarContentsSplitViewFolder SidebarContentsSplitView
            {
                get { return _sidebarcontentssplitview; }
            }
        }

        /// <summary>
        /// The SidebarContentsSplitViewFolder folder.
        /// </summary>
        [RepositoryFolder("37455347-449a-442d-844b-cef16039fa54")]
        public partial class SidebarContentsSplitViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginorregisterpagecontentInfo;
            RepoItemInfo _pleaseenterapasswordInfo;
            RepoItemInfo _agreeandsignupInfo;
            RepoItemInfo _continueInfo;
            RepoItemInfo _susiemail2945891388041464Info;

            /// <summary>
            /// Creates a new SidebarContentsSplitView  folder.
            /// </summary>
            public SidebarContentsSplitViewFolder(RepoGenBaseFolder parentFolder) :
                    base("SidebarContentsSplitView", "container[@name>'Register - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']", parentFolder, 30000, null, false, "37455347-449a-442d-844b-cef16039fa54", "")
            {
                _loginorregisterpagecontentInfo = new RepoItemInfo(this, "LoginOrRegisterPageContent", ".//container[@automationid='62673728']/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']", "", 30000, null, "f7bc5488-d65c-4278-8761-0e82ed552a3e");
                _pleaseenterapasswordInfo = new RepoItemInfo(this, "PleaseEnterAPassword", ".//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//container/text[@name='Please enter a password']", "", 30000, null, "4886d7cf-dcfd-42c7-9aa5-5140844f8cd4");
                _agreeandsignupInfo = new RepoItemInfo(this, "AgreeAndSignUp", "container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Agree and sign up']/?/?/text[@name='Agree and sign up']", "", 30000, null, "69078f9f-1009-49a4-bd08-544eda7f4854");
                _continueInfo = new RepoItemInfo(this, "Continue", "container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Continue']/?/?/text[@name='Continue']", "", 30000, null, "a4ea5e79-da82-4a55-8d35-1dcbfb868608");
                _susiemail2945891388041464Info = new RepoItemInfo(this, "SusiEmail2945891388041464", "container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//text[@automationid~'susi_email']", "", 30000, null, "6e59c07f-7e5c-4762-b5b5-c90c5436b782");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("37455347-449a-442d-844b-cef16039fa54")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("37455347-449a-442d-844b-cef16039fa54")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginOrRegisterPageContent item.
            /// </summary>
            [RepositoryItem("f7bc5488-d65c-4278-8761-0e82ed552a3e")]
            public virtual Ranorex.Container LoginOrRegisterPageContent
            {
                get
                {
                    return _loginorregisterpagecontentInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The LoginOrRegisterPageContent item info.
            /// </summary>
            [RepositoryItemInfo("f7bc5488-d65c-4278-8761-0e82ed552a3e")]
            public virtual RepoItemInfo LoginOrRegisterPageContentInfo
            {
                get
                {
                    return _loginorregisterpagecontentInfo;
                }
            }

            /// <summary>
            /// The PleaseEnterAPassword item.
            /// </summary>
            [RepositoryItem("4886d7cf-dcfd-42c7-9aa5-5140844f8cd4")]
            public virtual Ranorex.Text PleaseEnterAPassword
            {
                get
                {
                    return _pleaseenterapasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PleaseEnterAPassword item info.
            /// </summary>
            [RepositoryItemInfo("4886d7cf-dcfd-42c7-9aa5-5140844f8cd4")]
            public virtual RepoItemInfo PleaseEnterAPasswordInfo
            {
                get
                {
                    return _pleaseenterapasswordInfo;
                }
            }

            /// <summary>
            /// The AgreeAndSignUp item.
            /// </summary>
            [RepositoryItem("69078f9f-1009-49a4-bd08-544eda7f4854")]
            public virtual Ranorex.Text AgreeAndSignUp
            {
                get
                {
                    return _agreeandsignupInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AgreeAndSignUp item info.
            /// </summary>
            [RepositoryItemInfo("69078f9f-1009-49a4-bd08-544eda7f4854")]
            public virtual RepoItemInfo AgreeAndSignUpInfo
            {
                get
                {
                    return _agreeandsignupInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("a4ea5e79-da82-4a55-8d35-1dcbfb868608")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("a4ea5e79-da82-4a55-8d35-1dcbfb868608")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The SusiEmail2945891388041464 item.
            /// </summary>
            [RepositoryItem("6e59c07f-7e5c-4762-b5b5-c90c5436b782")]
            public virtual Ranorex.Text SusiEmail2945891388041464
            {
                get
                {
                    return _susiemail2945891388041464Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SusiEmail2945891388041464 item info.
            /// </summary>
            [RepositoryItemInfo("6e59c07f-7e5c-4762-b5b5-c90c5436b782")]
            public virtual RepoItemInfo SusiEmail2945891388041464Info
            {
                get
                {
                    return _susiemail2945891388041464Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
