///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace T16
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GoogleLogin recording.
    /// </summary>
    [TestModule("ad6eb192-61d0-488f-918b-5fb3271a2ec9", ModuleType.Recording, 1)]
    public partial class GoogleLogin : ITestModule
    {
        /// <summary>
        /// Holds an instance of the T16Repository repository.
        /// </summary>
        public static T16Repository repo = T16Repository.Instance;

        static GoogleLogin instance = new GoogleLogin();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GoogleLogin()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GoogleLogin Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginDropboxPersonalMicrosoftE.ContinueWithGoogle' at 48;5.", repo.LoginDropboxPersonalMicrosoftE.ContinueWithGoogleInfo, new RecordItemIndex(0));
            repo.LoginDropboxPersonalMicrosoftE.ContinueWithGoogle.Click("48;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Đăng nhập bằng Google') on item 'SignInGoogleAccountsPersonalM.ĐăngNhapBăngGoogle'.", repo.SignInGoogleAccountsPersonalM.ĐăngNhapBăngGoogleInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.SignInGoogleAccountsPersonalM.ĐăngNhapBăngGoogleInfo, "Text", "Đăng nhập bằng Google");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
