///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T16
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T16Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("85de23aa-169f-47c4-bb03-5d1aed409c17")]
    public partial class T16Repository : RepoGenBaseFolder
    {
        static T16Repository instance = new T16Repository();
        T16RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T16RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder _logindropboxpersonalmicrosofte;
        T16RepositoryFolders.SignInGoogleAccountsPersonalMAppFolder _signingoogleaccountspersonalm;

        /// <summary>
        /// Gets the singleton class instance representing the T16Repository element repository.
        /// </summary>
        [RepositoryFolder("85de23aa-169f-47c4-bb03-5d1aed409c17")]
        public static T16Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T16Repository() 
            : base("T16Repository", "/", null, 0, false, "85de23aa-169f-47c4-bb03-5d1aed409c17", ".\\RepositoryImages\\T16Repository85de23aa.rximgres")
        {
            _applicationundertest = new T16RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _logindropboxpersonalmicrosofte = new T16RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder(this);
            _signingoogleaccountspersonalm = new T16RepositoryFolders.SignInGoogleAccountsPersonalMAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("85de23aa-169f-47c4-bb03-5d1aed409c17")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("b1b8934e-6723-4172-99e9-8674816a51ed")]
        public virtual T16RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The LoginDropboxPersonalMicrosoftE folder.
        /// </summary>
        [RepositoryFolder("1fe0666e-3c4d-4cac-8443-21315560b0b1")]
        public virtual T16RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder LoginDropboxPersonalMicrosoftE
        {
            get { return _logindropboxpersonalmicrosofte; }
        }

        /// <summary>
        /// The SignInGoogleAccountsPersonalM folder.
        /// </summary>
        [RepositoryFolder("39982c39-ca95-4f91-96d1-12d6ff2df15a")]
        public virtual T16RepositoryFolders.SignInGoogleAccountsPersonalMAppFolder SignInGoogleAccountsPersonalM
        {
            get { return _signingoogleaccountspersonalm; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T16RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("b1b8934e-6723-4172-99e9-8674816a51ed")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "b1b8934e-6723-4172-99e9-8674816a51ed", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b1b8934e-6723-4172-99e9-8674816a51ed")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b1b8934e-6723-4172-99e9-8674816a51ed")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The LoginDropboxPersonalMicrosoftEAppFolder folder.
        /// </summary>
        [RepositoryFolder("1fe0666e-3c4d-4cac-8443-21315560b0b1")]
        public partial class LoginDropboxPersonalMicrosoftEAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _continuewithgoogleInfo;

            /// <summary>
            /// Creates a new LoginDropboxPersonalMicrosoftE  folder.
            /// </summary>
            public LoginDropboxPersonalMicrosoftEAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginDropboxPersonalMicrosoftE", "/form[@title>'Login - Dropbox - Personal']", parentFolder, 30000, null, true, "1fe0666e-3c4d-4cac-8443-21315560b0b1", "")
            {
                _continuewithgoogleInfo = new RepoItemInfo(this, "ContinueWithGoogle", "container[@name>'Login - Dropbox - Microsoft']//container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//container[@automationid='sign-in-with-google-button-container--login']//text/text[@name='Sign In - Google Accounts']/?/?/container[@automationid='container']/button[@name='Continue with Google']/?/?/text[@name='Continue with Google']", "", 30000, null, "dbda4339-68de-4580-9e96-dc57db30248e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1fe0666e-3c4d-4cac-8443-21315560b0b1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1fe0666e-3c4d-4cac-8443-21315560b0b1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContinueWithGoogle item.
            /// </summary>
            [RepositoryItem("dbda4339-68de-4580-9e96-dc57db30248e")]
            public virtual Ranorex.Text ContinueWithGoogle
            {
                get
                {
                    return _continuewithgoogleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContinueWithGoogle item info.
            /// </summary>
            [RepositoryItemInfo("dbda4339-68de-4580-9e96-dc57db30248e")]
            public virtual RepoItemInfo ContinueWithGoogleInfo
            {
                get
                {
                    return _continuewithgoogleInfo;
                }
            }
        }

        /// <summary>
        /// The SignInGoogleAccountsPersonalMAppFolder folder.
        /// </summary>
        [RepositoryFolder("39982c39-ca95-4f91-96d1-12d6ff2df15a")]
        public partial class SignInGoogleAccountsPersonalMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _đăngnhapbănggoogleInfo;

            /// <summary>
            /// Creates a new SignInGoogleAccountsPersonalM  folder.
            /// </summary>
            public SignInGoogleAccountsPersonalMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SignInGoogleAccountsPersonalM", "/form[@title>'Sign In - Google Accounts']", parentFolder, 30000, null, true, "39982c39-ca95-4f91-96d1-12d6ff2df15a", "")
            {
                _đăngnhapbănggoogleInfo = new RepoItemInfo(this, "ĐăngNhapBăngGoogle", "container[@name>'Sign In - Google Accounts']//container[@classname='SidebarContentsSplitView']//container/?/?/container[@automationid='container']/container[@automationid='main_dialog']/container[@automationid='banner']/container[@automationid='dialog_banner']/text[@name='Đăng nhập bằng Google']", "", 30000, null, "2cbe3d2a-4e81-4685-88dc-4d0f9f3f46a9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("39982c39-ca95-4f91-96d1-12d6ff2df15a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("39982c39-ca95-4f91-96d1-12d6ff2df15a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ĐăngNhapBăngGoogle item.
            /// </summary>
            [RepositoryItem("2cbe3d2a-4e81-4685-88dc-4d0f9f3f46a9")]
            public virtual Ranorex.Text ĐăngNhapBăngGoogle
            {
                get
                {
                    return _đăngnhapbănggoogleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ĐăngNhapBăngGoogle item info.
            /// </summary>
            [RepositoryItemInfo("2cbe3d2a-4e81-4685-88dc-4d0f9f3f46a9")]
            public virtual RepoItemInfo ĐăngNhapBăngGoogleInfo
            {
                get
                {
                    return _đăngnhapbănggoogleInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
