///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace T4
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RemoveSpace recording.
    /// </summary>
    [TestModule("b8330dba-e60e-4cf0-b7b2-bc9e298e60b8", ModuleType.Recording, 1)]
    public partial class RemoveSpace : ITestModule
    {
        /// <summary>
        /// Holds an instance of the T4Repository repository.
        /// </summary>
        public static T4Repository repo = T4Repository.Instance;

        static RemoveSpace instance = new RemoveSpace();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RemoveSpace()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RemoveSpace Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail6923959301162494' at 119;20.", repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail6923959301162494Info, new RecordItemIndex(0));
            repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail6923959301162494.Click("119;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '                    askudaksgdhajhsgdkja{h up}gdkhagsd@gmail.com           ' with focus on 'RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail6923959301162494'.", repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail6923959301162494Info, new RecordItemIndex(1));
            repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail6923959301162494.PressKeys("                    askudaksgdhajhsgdkja{h up}gdkhagsd@gmail.com           ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.Continue' at 46;9.", repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.ContinueInfo, new RecordItemIndex(2));
            repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.Continue.Click("46;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Agree and sign up') on item 'RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.AgreeAndSignUp'.", repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.AgreeAndSignUpInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.AgreeAndSignUpInfo, "Text", "Agree and sign up");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
