///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T4
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T4Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("4cbc8979-2e44-48cc-8033-06357ad21dc8")]
    public partial class T4Repository : RepoGenBaseFolder
    {
        static T4Repository instance = new T4Repository();
        T4RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T4RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder _registerdropboxpersonalmicrosof;

        /// <summary>
        /// Gets the singleton class instance representing the T4Repository element repository.
        /// </summary>
        [RepositoryFolder("4cbc8979-2e44-48cc-8033-06357ad21dc8")]
        public static T4Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T4Repository() 
            : base("T4Repository", "/", null, 0, false, "4cbc8979-2e44-48cc-8033-06357ad21dc8", ".\\RepositoryImages\\T4Repository4cbc8979.rximgres")
        {
            _applicationundertest = new T4RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _registerdropboxpersonalmicrosof = new T4RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4cbc8979-2e44-48cc-8033-06357ad21dc8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("cfe50450-6846-4458-a2b9-003ec66ecc27")]
        public virtual T4RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosof folder.
        /// </summary>
        [RepositoryFolder("cde9623f-5eef-4868-b3f6-3877c878367b")]
        public virtual T4RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder RegisterDropboxPersonalMicrosof
        {
            get { return _registerdropboxpersonalmicrosof; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T4RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("cfe50450-6846-4458-a2b9-003ec66ecc27")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "cfe50450-6846-4458-a2b9-003ec66ecc27", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cfe50450-6846-4458-a2b9-003ec66ecc27")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cfe50450-6846-4458-a2b9-003ec66ecc27")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosofAppFolder folder.
        /// </summary>
        [RepositoryFolder("cde9623f-5eef-4868-b3f6-3877c878367b")]
        public partial class RegisterDropboxPersonalMicrosofAppFolder : RepoGenBaseFolder
        {
            T4RepositoryFolders.LoginOrRegisterPageContentFolder _loginorregisterpagecontent;

            /// <summary>
            /// Creates a new RegisterDropboxPersonalMicrosof  folder.
            /// </summary>
            public RegisterDropboxPersonalMicrosofAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterDropboxPersonalMicrosof", "/form[@title>'Register - Dropbox - Personal']", parentFolder, 30000, null, true, "cde9623f-5eef-4868-b3f6-3877c878367b", "")
            {
                _loginorregisterpagecontent = new T4RepositoryFolders.LoginOrRegisterPageContentFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cde9623f-5eef-4868-b3f6-3877c878367b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cde9623f-5eef-4868-b3f6-3877c878367b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginOrRegisterPageContent folder.
            /// </summary>
            [RepositoryFolder("aff3eede-dbc7-498a-89a9-54e7eb5e0576")]
            public virtual T4RepositoryFolders.LoginOrRegisterPageContentFolder LoginOrRegisterPageContent
            {
                get { return _loginorregisterpagecontent; }
            }
        }

        /// <summary>
        /// The LoginOrRegisterPageContentFolder folder.
        /// </summary>
        [RepositoryFolder("aff3eede-dbc7-498a-89a9-54e7eb5e0576")]
        public partial class LoginOrRegisterPageContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _agreeandsignupInfo;
            RepoItemInfo _continueInfo;
            RepoItemInfo _susiemail6923959301162494Info;

            /// <summary>
            /// Creates a new LoginOrRegisterPageContent  folder.
            /// </summary>
            public LoginOrRegisterPageContentFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginOrRegisterPageContent", "container[@name>'Register - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']", parentFolder, 30000, null, false, "aff3eede-dbc7-498a-89a9-54e7eb5e0576", "")
            {
                _agreeandsignupInfo = new RepoItemInfo(this, "AgreeAndSignUp", ".//button[@name='Agree and sign up']/?/?/text[@name='Agree and sign up']", "", 30000, null, "555744c1-57ae-45d3-a10d-d587d4540f6d");
                _continueInfo = new RepoItemInfo(this, "Continue", ".//button[@name='Continue']/?/?/text[@name='Continue']", "", 30000, null, "e18002e0-ca2b-48e4-9037-a36090e41b7c");
                _susiemail6923959301162494Info = new RepoItemInfo(this, "SusiEmail6923959301162494", ".//text[@automationid~'susi_email']", "", 30000, null, "347c3b18-a33c-4036-b06b-96a5820b5cf8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aff3eede-dbc7-498a-89a9-54e7eb5e0576")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aff3eede-dbc7-498a-89a9-54e7eb5e0576")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AgreeAndSignUp item.
            /// </summary>
            [RepositoryItem("555744c1-57ae-45d3-a10d-d587d4540f6d")]
            public virtual Ranorex.Text AgreeAndSignUp
            {
                get
                {
                    return _agreeandsignupInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AgreeAndSignUp item info.
            /// </summary>
            [RepositoryItemInfo("555744c1-57ae-45d3-a10d-d587d4540f6d")]
            public virtual RepoItemInfo AgreeAndSignUpInfo
            {
                get
                {
                    return _agreeandsignupInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("e18002e0-ca2b-48e4-9037-a36090e41b7c")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("e18002e0-ca2b-48e4-9037-a36090e41b7c")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The SusiEmail6923959301162494 item.
            /// </summary>
            [RepositoryItem("347c3b18-a33c-4036-b06b-96a5820b5cf8")]
            public virtual Ranorex.Text SusiEmail6923959301162494
            {
                get
                {
                    return _susiemail6923959301162494Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SusiEmail6923959301162494 item info.
            /// </summary>
            [RepositoryItemInfo("347c3b18-a33c-4036-b06b-96a5820b5cf8")]
            public virtual RepoItemInfo SusiEmail6923959301162494Info
            {
                get
                {
                    return _susiemail6923959301162494Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
