///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T9
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T9Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f20a933b-c22b-44a2-8a82-ded9e42ec92d")]
    public partial class T9Repository : RepoGenBaseFolder
    {
        static T9Repository instance = new T9Repository();
        T9RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T9RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder _registerdropboxpersonalmicrosof;

        /// <summary>
        /// Gets the singleton class instance representing the T9Repository element repository.
        /// </summary>
        [RepositoryFolder("f20a933b-c22b-44a2-8a82-ded9e42ec92d")]
        public static T9Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T9Repository() 
            : base("T9Repository", "/", null, 0, false, "f20a933b-c22b-44a2-8a82-ded9e42ec92d", ".\\RepositoryImages\\T9Repositoryf20a933b.rximgres")
        {
            _applicationundertest = new T9RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _registerdropboxpersonalmicrosof = new T9RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f20a933b-c22b-44a2-8a82-ded9e42ec92d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("9e552d88-29d6-4d6a-82f6-d0023246fb72")]
        public virtual T9RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosof folder.
        /// </summary>
        [RepositoryFolder("1b286468-8543-48ad-a9ed-bf1bd3117771")]
        public virtual T9RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder RegisterDropboxPersonalMicrosof
        {
            get { return _registerdropboxpersonalmicrosof; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T9RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("9e552d88-29d6-4d6a-82f6-d0023246fb72")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "9e552d88-29d6-4d6a-82f6-d0023246fb72", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9e552d88-29d6-4d6a-82f6-d0023246fb72")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9e552d88-29d6-4d6a-82f6-d0023246fb72")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosofAppFolder folder.
        /// </summary>
        [RepositoryFolder("1b286468-8543-48ad-a9ed-bf1bd3117771")]
        public partial class RegisterDropboxPersonalMicrosofAppFolder : RepoGenBaseFolder
        {
            T9RepositoryFolders.SidebarContentsSplitViewFolder _sidebarcontentssplitview;

            /// <summary>
            /// Creates a new RegisterDropboxPersonalMicrosof  folder.
            /// </summary>
            public RegisterDropboxPersonalMicrosofAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterDropboxPersonalMicrosof", "/form[@title>'Register - Dropbox - Personal']", parentFolder, 30000, null, true, "1b286468-8543-48ad-a9ed-bf1bd3117771", "")
            {
                _sidebarcontentssplitview = new T9RepositoryFolders.SidebarContentsSplitViewFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1b286468-8543-48ad-a9ed-bf1bd3117771")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1b286468-8543-48ad-a9ed-bf1bd3117771")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SidebarContentsSplitView folder.
            /// </summary>
            [RepositoryFolder("aac29e82-70c0-4273-881e-57d59bab4e23")]
            public virtual T9RepositoryFolders.SidebarContentsSplitViewFolder SidebarContentsSplitView
            {
                get { return _sidebarcontentssplitview; }
            }
        }

        /// <summary>
        /// The SidebarContentsSplitViewFolder folder.
        /// </summary>
        [RepositoryFolder("aac29e82-70c0-4273-881e-57d59bab4e23")]
        public partial class SidebarContentsSplitViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _susiemail2945891388041464Info;
            RepoItemInfo _continueInfo;
            RepoItemInfo _agreeandsignupInfo;
            RepoItemInfo _pleaseenteryourfirstnameInfo;

            /// <summary>
            /// Creates a new SidebarContentsSplitView  folder.
            /// </summary>
            public SidebarContentsSplitViewFolder(RepoGenBaseFolder parentFolder) :
                    base("SidebarContentsSplitView", "container[@name>'Register - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']", parentFolder, 30000, null, false, "aac29e82-70c0-4273-881e-57d59bab4e23", "")
            {
                _susiemail2945891388041464Info = new RepoItemInfo(this, "SusiEmail2945891388041464", "container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//text[@automationid~'susi_email']", "", 30000, null, "2836d685-3239-465c-93a5-7245ee4b74bd");
                _continueInfo = new RepoItemInfo(this, "Continue", "container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Continue']/?/?/text[@name='Continue']", "", 30000, null, "41567236-4c8d-4e11-97d9-096c38acca62");
                _agreeandsignupInfo = new RepoItemInfo(this, "AgreeAndSignUp", "container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Agree and sign up']/?/?/text[@name='Agree and sign up']", "", 30000, null, "48920f64-87db-4621-b221-8f32b53df686");
                _pleaseenteryourfirstnameInfo = new RepoItemInfo(this, "PleaseEnterYourFirstName", ".//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//container/text[@name>'Please enter your first n']", "", 30000, null, "f04f4b62-f5a6-4a1e-96ac-bf1135a4327d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aac29e82-70c0-4273-881e-57d59bab4e23")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aac29e82-70c0-4273-881e-57d59bab4e23")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SusiEmail2945891388041464 item.
            /// </summary>
            [RepositoryItem("2836d685-3239-465c-93a5-7245ee4b74bd")]
            public virtual Ranorex.Text SusiEmail2945891388041464
            {
                get
                {
                    return _susiemail2945891388041464Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SusiEmail2945891388041464 item info.
            /// </summary>
            [RepositoryItemInfo("2836d685-3239-465c-93a5-7245ee4b74bd")]
            public virtual RepoItemInfo SusiEmail2945891388041464Info
            {
                get
                {
                    return _susiemail2945891388041464Info;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("41567236-4c8d-4e11-97d9-096c38acca62")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("41567236-4c8d-4e11-97d9-096c38acca62")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The AgreeAndSignUp item.
            /// </summary>
            [RepositoryItem("48920f64-87db-4621-b221-8f32b53df686")]
            public virtual Ranorex.Text AgreeAndSignUp
            {
                get
                {
                    return _agreeandsignupInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AgreeAndSignUp item info.
            /// </summary>
            [RepositoryItemInfo("48920f64-87db-4621-b221-8f32b53df686")]
            public virtual RepoItemInfo AgreeAndSignUpInfo
            {
                get
                {
                    return _agreeandsignupInfo;
                }
            }

            /// <summary>
            /// The PleaseEnterYourFirstName item.
            /// </summary>
            [RepositoryItem("f04f4b62-f5a6-4a1e-96ac-bf1135a4327d")]
            public virtual Ranorex.Text PleaseEnterYourFirstName
            {
                get
                {
                    return _pleaseenteryourfirstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PleaseEnterYourFirstName item info.
            /// </summary>
            [RepositoryItemInfo("f04f4b62-f5a6-4a1e-96ac-bf1135a4327d")]
            public virtual RepoItemInfo PleaseEnterYourFirstNameInfo
            {
                get
                {
                    return _pleaseenteryourfirstnameInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
