///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T22
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T22Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e9394b56-c333-44c2-b08d-5bab9e931302")]
    public partial class T22Repository : RepoGenBaseFolder
    {
        static T22Repository instance = new T22Repository();
        T22RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T22RepositoryFolders.FilesDropboxPersonalMicrosoftEAppFolder _filesdropboxpersonalmicrosofte;

        /// <summary>
        /// Gets the singleton class instance representing the T22Repository element repository.
        /// </summary>
        [RepositoryFolder("e9394b56-c333-44c2-b08d-5bab9e931302")]
        public static T22Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T22Repository() 
            : base("T22Repository", "/", null, 0, false, "e9394b56-c333-44c2-b08d-5bab9e931302", ".\\RepositoryImages\\T22Repositorye9394b56.rximgres")
        {
            _applicationundertest = new T22RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _filesdropboxpersonalmicrosofte = new T22RepositoryFolders.FilesDropboxPersonalMicrosoftEAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e9394b56-c333-44c2-b08d-5bab9e931302")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("3efe49bb-3040-450e-a91e-271bb32f7266")]
        public virtual T22RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The FilesDropboxPersonalMicrosoftE folder.
        /// </summary>
        [RepositoryFolder("489ea2ad-7df0-4f33-b6d4-421dc04cb09d")]
        public virtual T22RepositoryFolders.FilesDropboxPersonalMicrosoftEAppFolder FilesDropboxPersonalMicrosoftE
        {
            get { return _filesdropboxpersonalmicrosofte; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T22RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("3efe49bb-3040-450e-a91e-271bb32f7266")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "3efe49bb-3040-450e-a91e-271bb32f7266", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3efe49bb-3040-450e-a91e-271bb32f7266")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3efe49bb-3040-450e-a91e-271bb32f7266")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The FilesDropboxPersonalMicrosoftEAppFolder folder.
        /// </summary>
        [RepositoryFolder("489ea2ad-7df0-4f33-b6d4-421dc04cb09d")]
        public partial class FilesDropboxPersonalMicrosoftEAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _uploadordropInfo;
            RepoItemInfo _digmenucontentdigmenucontentbottoInfo;

            /// <summary>
            /// Creates a new FilesDropboxPersonalMicrosoftE  folder.
            /// </summary>
            public FilesDropboxPersonalMicrosoftEAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FilesDropboxPersonalMicrosoftE", "/form[@title>'Files - Dropbox - Personal']", parentFolder, 30000, null, true, "489ea2ad-7df0-4f33-b6d4-421dc04cb09d", "")
            {
                _uploadordropInfo = new RepoItemInfo(this, "UploadOrDrop", "container[@name>'Files - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@orientation='None' and @iscontentelement='True']/?/?/container/text[@name='Files - Dropbox']/container[@classname='global-header--portaled']/container[@automationid='maestro-portal']/container[@automationid='maestro-content-portal']//container[@classname='_browseActionBarWrapper_12ja8_4 _actionBarWrapper_cxckl_9 _actionBarWrapperIntersectionOnly_cxckl_36']//button[@name='Upload or Drop']", "", 30000, null, "38c44402-6be1-49b1-840f-a363dfbdf04f");
                _digmenucontentdigmenucontentbottoInfo = new RepoItemInfo(this, "DigMenuContentDigMenuContentBotto", "container[@name>'Files - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Files - Dropbox']/container[@classname='global-header--portaled']/container[@classname='dig-Layer']/?/?/contextmenu[@classname='dig-Menu-content dig-Menu-content--bottom-start']", "", 30000, null, "a28155e5-0ae3-49db-b319-7c08c964f81c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("489ea2ad-7df0-4f33-b6d4-421dc04cb09d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("489ea2ad-7df0-4f33-b6d4-421dc04cb09d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UploadOrDrop item.
            /// </summary>
            [RepositoryItem("38c44402-6be1-49b1-840f-a363dfbdf04f")]
            public virtual Ranorex.Button UploadOrDrop
            {
                get
                {
                    return _uploadordropInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UploadOrDrop item info.
            /// </summary>
            [RepositoryItemInfo("38c44402-6be1-49b1-840f-a363dfbdf04f")]
            public virtual RepoItemInfo UploadOrDropInfo
            {
                get
                {
                    return _uploadordropInfo;
                }
            }

            /// <summary>
            /// The DigMenuContentDigMenuContentBotto item.
            /// </summary>
            [RepositoryItem("a28155e5-0ae3-49db-b319-7c08c964f81c")]
            public virtual Ranorex.ContextMenu DigMenuContentDigMenuContentBotto
            {
                get
                {
                    return _digmenucontentdigmenucontentbottoInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The DigMenuContentDigMenuContentBotto item info.
            /// </summary>
            [RepositoryItemInfo("a28155e5-0ae3-49db-b319-7c08c964f81c")]
            public virtual RepoItemInfo DigMenuContentDigMenuContentBottoInfo
            {
                get
                {
                    return _digmenucontentdigmenucontentbottoInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
