///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T20
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T20Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6a80d9c0-0099-4caa-a2fa-8439624ebb78")]
    public partial class T20Repository : RepoGenBaseFolder
    {
        static T20Repository instance = new T20Repository();
        T20RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T20RepositoryFolders.FilesDropboxPersonalMicrosoftEAppFolder _filesdropboxpersonalmicrosofte;
        T20RepositoryFolders.SearchResultsDropboxPersonalMiAppFolder _searchresultsdropboxpersonalmi;

        /// <summary>
        /// Gets the singleton class instance representing the T20Repository element repository.
        /// </summary>
        [RepositoryFolder("6a80d9c0-0099-4caa-a2fa-8439624ebb78")]
        public static T20Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T20Repository() 
            : base("T20Repository", "/", null, 0, false, "6a80d9c0-0099-4caa-a2fa-8439624ebb78", ".\\RepositoryImages\\T20Repository6a80d9c0.rximgres")
        {
            _applicationundertest = new T20RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _filesdropboxpersonalmicrosofte = new T20RepositoryFolders.FilesDropboxPersonalMicrosoftEAppFolder(this);
            _searchresultsdropboxpersonalmi = new T20RepositoryFolders.SearchResultsDropboxPersonalMiAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6a80d9c0-0099-4caa-a2fa-8439624ebb78")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("a4338704-c0d1-47d6-b8c1-90697421a3f1")]
        public virtual T20RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The FilesDropboxPersonalMicrosoftE folder.
        /// </summary>
        [RepositoryFolder("c2907427-40b8-48e9-966f-fd3c6a6ebf18")]
        public virtual T20RepositoryFolders.FilesDropboxPersonalMicrosoftEAppFolder FilesDropboxPersonalMicrosoftE
        {
            get { return _filesdropboxpersonalmicrosofte; }
        }

        /// <summary>
        /// The SearchResultsDropboxPersonalMi folder.
        /// </summary>
        [RepositoryFolder("1922df22-dfc9-4559-8fea-a0878dd235af")]
        public virtual T20RepositoryFolders.SearchResultsDropboxPersonalMiAppFolder SearchResultsDropboxPersonalMi
        {
            get { return _searchresultsdropboxpersonalmi; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T20RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("a4338704-c0d1-47d6-b8c1-90697421a3f1")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "a4338704-c0d1-47d6-b8c1-90697421a3f1", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a4338704-c0d1-47d6-b8c1-90697421a3f1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a4338704-c0d1-47d6-b8c1-90697421a3f1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The FilesDropboxPersonalMicrosoftEAppFolder folder.
        /// </summary>
        [RepositoryFolder("c2907427-40b8-48e9-966f-fd3c6a6ebf18")]
        public partial class FilesDropboxPersonalMicrosoftEAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _searchinfolderdropboxInfo;

            /// <summary>
            /// Creates a new FilesDropboxPersonalMicrosoftE  folder.
            /// </summary>
            public FilesDropboxPersonalMicrosoftEAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FilesDropboxPersonalMicrosoftE", "/form[@title>'Files - Dropbox - Personal']", parentFolder, 30000, null, true, "c2907427-40b8-48e9-966f-fd3c6a6ebf18", "")
            {
                _searchinfolderdropboxInfo = new RepoItemInfo(this, "SearchInFolderDropbox", "container[@name>'Files - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']//container[@automationid>'']/text[@name='Files - Dropbox']/container[@classname='global-header--portaled']/container[@automationid='maestro-portal']/container[@automationid='global-header-portal']/container[@name='Global header']/container[@classname='_search-input-portal-web-redesign_kxyvl_8']//combobox[@name>'Search in folder “Dropbox']", ".//combobox[@name>'Search in folder “Dropbox']", 30000, null, "73b6978a-0cc7-4b7b-83c8-974ce3e00d48");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c2907427-40b8-48e9-966f-fd3c6a6ebf18")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c2907427-40b8-48e9-966f-fd3c6a6ebf18")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SearchInFolderDropbox item.
            /// </summary>
            [RepositoryItem("73b6978a-0cc7-4b7b-83c8-974ce3e00d48")]
            public virtual Ranorex.ComboBox SearchInFolderDropbox
            {
                get
                {
                    return _searchinfolderdropboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The SearchInFolderDropbox item info.
            /// </summary>
            [RepositoryItemInfo("73b6978a-0cc7-4b7b-83c8-974ce3e00d48")]
            public virtual RepoItemInfo SearchInFolderDropboxInfo
            {
                get
                {
                    return _searchinfolderdropboxInfo;
                }
            }
        }

        /// <summary>
        /// The SearchResultsDropboxPersonalMiAppFolder folder.
        /// </summary>
        [RepositoryFolder("1922df22-dfc9-4559-8fea-a0878dd235af")]
        public partial class SearchResultsDropboxPersonalMiAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _noresultsfoundInfo;
            RepoItemInfo _searchinfolderdropboxInfo;

            /// <summary>
            /// Creates a new SearchResultsDropboxPersonalMi  folder.
            /// </summary>
            public SearchResultsDropboxPersonalMiAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SearchResultsDropboxPersonalMi", "/form[@title>'Search results - Dropbox -']", parentFolder, 30000, null, true, "1922df22-dfc9-4559-8fea-a0878dd235af", "")
            {
                _noresultsfoundInfo = new RepoItemInfo(this, "NoResultsFound", "container[@name>'Search results - Dropbox -']//container[@classname='SidebarContentsSplitView']//container[@automationid>'']/?/?/container[@classname='global-header--portaled']/container[@automationid='maestro-portal']/container[@automationid='maestro-content-portal']/?/?/container[@classname='_search-view-container-web-redesign-without-section-component_7vhv8_3']/container[@automationid='search-view']/text[@name='No results found']/text[@name='No results found']", "", 30000, null, "fd93580e-e709-47e0-ba89-3c819562cc6a");
                _searchinfolderdropboxInfo = new RepoItemInfo(this, "SearchInFolderDropbox", "container[@name>'Search results - Dropbox -']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']//container[@automationid>'']/text[@name='Search results - Dropbox']/container[@classname='global-header--portaled']/container[@automationid='maestro-portal']/container[@automationid='global-header-portal']/container[@name='Global header']/container[@classname='_search-input-portal-web-redesign_kxyvl_8']//combobox[@name>'Search in folder “Dropbox']", "", 30000, null, "312e8942-13c2-4a65-9e52-8df7d372e8e4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1922df22-dfc9-4559-8fea-a0878dd235af")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1922df22-dfc9-4559-8fea-a0878dd235af")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NoResultsFound item.
            /// </summary>
            [RepositoryItem("fd93580e-e709-47e0-ba89-3c819562cc6a")]
            public virtual Ranorex.Text NoResultsFound
            {
                get
                {
                    return _noresultsfoundInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NoResultsFound item info.
            /// </summary>
            [RepositoryItemInfo("fd93580e-e709-47e0-ba89-3c819562cc6a")]
            public virtual RepoItemInfo NoResultsFoundInfo
            {
                get
                {
                    return _noresultsfoundInfo;
                }
            }

            /// <summary>
            /// The SearchInFolderDropbox item.
            /// </summary>
            [RepositoryItem("312e8942-13c2-4a65-9e52-8df7d372e8e4")]
            public virtual Ranorex.ComboBox SearchInFolderDropbox
            {
                get
                {
                    return _searchinfolderdropboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The SearchInFolderDropbox item info.
            /// </summary>
            [RepositoryItemInfo("312e8942-13c2-4a65-9e52-8df7d372e8e4")]
            public virtual RepoItemInfo SearchInFolderDropboxInfo
            {
                get
                {
                    return _searchinfolderdropboxInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
