///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace T3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LengthLimitEmail recording.
    /// </summary>
    [TestModule("262d8e0d-3e42-43a0-b5a2-e919205524df", ModuleType.Recording, 1)]
    public partial class LengthLimitEmail : ITestModule
    {
        /// <summary>
        /// Holds an instance of the T3Repository repository.
        /// </summary>
        public static T3Repository repo = T3Repository.Instance;

        static LengthLimitEmail instance = new LengthLimitEmail();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LengthLimitEmail()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LengthLimitEmail Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RegisterDropboxPersonalMicrosof.RegisterDropboxMicrosoftEdgePe.SusiEmail5097574413718853' at 68;25.", repo.RegisterDropboxPersonalMicrosof.RegisterDropboxMicrosoftEdgePe.SusiEmail5097574413718853Info, new RecordItemIndex(0));
            repo.RegisterDropboxPersonalMicrosof.RegisterDropboxMicrosoftEdgePe.SusiEmail5097574413718853.Click("68;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'kadfasdiofuaosdufsjkdfioasfklhsdflsdhfiousuiofweiuhskdjfjkaskhgdfiuwasfhjgsfhjgsaufgsuijdhfgbajshgfuywegjkhbdsjkhsgudjfhbwjkehgfajksdbfjkhsagfuwyeg7688ty2834ydhjkfjkatsdyfagsdukfgauiebfjkahsdgf87ity8i73tyr4irjkbsiuo7tydf8i73gjhwbfjhksgi8f7wt3yg8wfgbshjdgf877g47fu4j3bfjsktf7ytw83fgbwkhdg@gmaill.com' with focus on 'RegisterDropboxPersonalMicrosof.RegisterDropboxMicrosoftEdgePe.SusiEmail5097574413718853'.", repo.RegisterDropboxPersonalMicrosof.RegisterDropboxMicrosoftEdgePe.SusiEmail5097574413718853Info, new RecordItemIndex(1));
            repo.RegisterDropboxPersonalMicrosof.RegisterDropboxMicrosoftEdgePe.SusiEmail5097574413718853.PressKeys("kadfasdiofuaosdufsjkdfioasfklhsdflsdhfiousuiofweiuhskdjfjkaskhgdfiuwasfhjgsfhjgsaufgsuijdhfgbajshgfuywegjkhbdsjkhsgudjfhbwjkehgfajksdbfjkhsagfuwyeg7688ty2834ydhjkfjkatsdyfagsdukfgauiebfjkahsdgf87ity8i73tyr4irjkbsiuo7tydf8i73gjhwbfjhksgi8f7wt3yg8wfgbshjdgf877g47fu4j3bfjsktf7ytw83fgbwkhdg@gmaill.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RegisterDropboxPersonalMicrosof.RegisterDropboxMicrosoftEdgePe.Continue' at 38;13.", repo.RegisterDropboxPersonalMicrosof.RegisterDropboxMicrosoftEdgePe.ContinueInfo, new RecordItemIndex(2));
            repo.RegisterDropboxPersonalMicrosof.RegisterDropboxMicrosoftEdgePe.Continue.Click("38;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RegisterDropboxPersonalMicrosof.RegisterDropboxMicrosoftEdgePe.InvalidEmail'.", repo.RegisterDropboxPersonalMicrosof.RegisterDropboxMicrosoftEdgePe.InvalidEmailInfo, new RecordItemIndex(3));
            Validate.Exists(repo.RegisterDropboxPersonalMicrosof.RegisterDropboxMicrosoftEdgePe.InvalidEmailInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
