///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T3Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b44a3f99-15d2-4c3d-a323-cef6df6390c0")]
    public partial class T3Repository : RepoGenBaseFolder
    {
        static T3Repository instance = new T3Repository();
        T3RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T3RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder _registerdropboxpersonalmicrosof;

        /// <summary>
        /// Gets the singleton class instance representing the T3Repository element repository.
        /// </summary>
        [RepositoryFolder("b44a3f99-15d2-4c3d-a323-cef6df6390c0")]
        public static T3Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T3Repository() 
            : base("T3Repository", "/", null, 0, false, "b44a3f99-15d2-4c3d-a323-cef6df6390c0", ".\\RepositoryImages\\T3Repositoryb44a3f99.rximgres")
        {
            _applicationundertest = new T3RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _registerdropboxpersonalmicrosof = new T3RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b44a3f99-15d2-4c3d-a323-cef6df6390c0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("eaf93910-0889-48ff-93b1-69686558e99b")]
        public virtual T3RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosof folder.
        /// </summary>
        [RepositoryFolder("b12d0f18-3677-4b03-9a6b-8c15c26baf0a")]
        public virtual T3RepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder RegisterDropboxPersonalMicrosof
        {
            get { return _registerdropboxpersonalmicrosof; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T3RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("eaf93910-0889-48ff-93b1-69686558e99b")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "eaf93910-0889-48ff-93b1-69686558e99b", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eaf93910-0889-48ff-93b1-69686558e99b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eaf93910-0889-48ff-93b1-69686558e99b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosofAppFolder folder.
        /// </summary>
        [RepositoryFolder("b12d0f18-3677-4b03-9a6b-8c15c26baf0a")]
        public partial class RegisterDropboxPersonalMicrosofAppFolder : RepoGenBaseFolder
        {
            T3RepositoryFolders.RegisterDropboxMicrosoftEdgePeFolder _registerdropboxmicrosoftedgepe;

            /// <summary>
            /// Creates a new RegisterDropboxPersonalMicrosof  folder.
            /// </summary>
            public RegisterDropboxPersonalMicrosofAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterDropboxPersonalMicrosof", "/form[@title>'Register - Dropbox - Personal']", parentFolder, 30000, null, true, "b12d0f18-3677-4b03-9a6b-8c15c26baf0a", "")
            {
                _registerdropboxmicrosoftedgepe = new T3RepositoryFolders.RegisterDropboxMicrosoftEdgePeFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b12d0f18-3677-4b03-9a6b-8c15c26baf0a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b12d0f18-3677-4b03-9a6b-8c15c26baf0a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RegisterDropboxMicrosoftEdgePe folder.
            /// </summary>
            [RepositoryFolder("4a99c6dd-9302-4cde-876e-3a1dd75c0cd0")]
            public virtual T3RepositoryFolders.RegisterDropboxMicrosoftEdgePeFolder RegisterDropboxMicrosoftEdgePe
            {
                get { return _registerdropboxmicrosoftedgepe; }
            }
        }

        /// <summary>
        /// The RegisterDropboxMicrosoftEdgePeFolder folder.
        /// </summary>
        [RepositoryFolder("4a99c6dd-9302-4cde-876e-3a1dd75c0cd0")]
        public partial class RegisterDropboxMicrosoftEdgePeFolder : RepoGenBaseFolder
        {
            RepoItemInfo _continueInfo;
            RepoItemInfo _susiemail5097574413718853Info;
            RepoItemInfo _invalidemailInfo;

            /// <summary>
            /// Creates a new RegisterDropboxMicrosoftEdgePe  folder.
            /// </summary>
            public RegisterDropboxMicrosoftEdgePeFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterDropboxMicrosoftEdgePe", "container[@name>'Register - Dropbox - Microsoft']", parentFolder, 30000, null, false, "4a99c6dd-9302-4cde-876e-3a1dd75c0cd0", "")
            {
                _continueInfo = new RepoItemInfo(this, "Continue", ".//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Continue']/?/?/text[@name='Continue']", "", 30000, null, "3ec7908e-d23f-4632-8c6d-71112c8ac11f");
                _susiemail5097574413718853Info = new RepoItemInfo(this, "SusiEmail5097574413718853", ".//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//text[@automationid~'susi_email']", "", 30000, null, "c4956fae-e346-4482-a3a7-a513dd6e597f");
                _invalidemailInfo = new RepoItemInfo(this, "InvalidEmail", ".//container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//container/text[@name='Invalid email']", "", 30000, null, "bf1b4a66-b88d-465a-a72b-8024168d13a4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4a99c6dd-9302-4cde-876e-3a1dd75c0cd0")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4a99c6dd-9302-4cde-876e-3a1dd75c0cd0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("3ec7908e-d23f-4632-8c6d-71112c8ac11f")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("3ec7908e-d23f-4632-8c6d-71112c8ac11f")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The SusiEmail5097574413718853 item.
            /// </summary>
            [RepositoryItem("c4956fae-e346-4482-a3a7-a513dd6e597f")]
            public virtual Ranorex.Text SusiEmail5097574413718853
            {
                get
                {
                    return _susiemail5097574413718853Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SusiEmail5097574413718853 item info.
            /// </summary>
            [RepositoryItemInfo("c4956fae-e346-4482-a3a7-a513dd6e597f")]
            public virtual RepoItemInfo SusiEmail5097574413718853Info
            {
                get
                {
                    return _susiemail5097574413718853Info;
                }
            }

            /// <summary>
            /// The InvalidEmail item.
            /// </summary>
            [RepositoryItem("bf1b4a66-b88d-465a-a72b-8024168d13a4")]
            public virtual Ranorex.Text InvalidEmail
            {
                get
                {
                    return _invalidemailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The InvalidEmail item info.
            /// </summary>
            [RepositoryItemInfo("bf1b4a66-b88d-465a-a72b-8024168d13a4")]
            public virtual RepoItemInfo InvalidEmailInfo
            {
                get
                {
                    return _invalidemailInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
