///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EmailFormat recording.
    /// </summary>
    [TestModule("5ba6c116-7ff9-4969-ba3b-c29684f46fb3", ModuleType.Recording, 1)]
    public partial class EmailFormat : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static EmailFormat instance = new EmailFormat();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EmailFormat()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EmailFormat Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail12233782113174296' at 124;15.", repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail12233782113174296Info, new RecordItemIndex(0));
            repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail12233782113174296.Click("124;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aád@v' with focus on 'RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail12233782113174296'.", repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail12233782113174296Info, new RecordItemIndex(1));
            repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail12233782113174296.PressKeys("aád@v");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.Continue' at 28;13.", repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.ContinueInfo, new RecordItemIndex(2));
            repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.Continue.Click("28;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail12233782113174296InputError'.", repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail12233782113174296InputErrorInfo, new RecordItemIndex(3));
            Validate.Exists(repo.RegisterDropboxPersonalMicrosof.LoginOrRegisterPageContent.SusiEmail12233782113174296InputErrorInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
