///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("8cf66245-dedc-4545-a92a-9119f62d882a")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyTestRepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder _registerdropboxpersonalmicrosof;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("8cf66245-dedc-4545-a92a-9119f62d882a")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "8cf66245-dedc-4545-a92a-9119f62d882a", ".\\RepositoryImages\\MyTestRepository8cf66245.rximgres")
        {
            _applicationundertest = new MyTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _registerdropboxpersonalmicrosof = new MyTestRepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8cf66245-dedc-4545-a92a-9119f62d882a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("015a48c6-0a97-46f1-a36e-94f48282cfc8")]
        public virtual MyTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosof folder.
        /// </summary>
        [RepositoryFolder("9469a224-bd77-41fa-b7b4-a304c1da3a81")]
        public virtual MyTestRepositoryFolders.RegisterDropboxPersonalMicrosofAppFolder RegisterDropboxPersonalMicrosof
        {
            get { return _registerdropboxpersonalmicrosof; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("015a48c6-0a97-46f1-a36e-94f48282cfc8")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "015a48c6-0a97-46f1-a36e-94f48282cfc8", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("015a48c6-0a97-46f1-a36e-94f48282cfc8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("015a48c6-0a97-46f1-a36e-94f48282cfc8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterDropboxPersonalMicrosofAppFolder folder.
        /// </summary>
        [RepositoryFolder("9469a224-bd77-41fa-b7b4-a304c1da3a81")]
        public partial class RegisterDropboxPersonalMicrosofAppFolder : RepoGenBaseFolder
        {
            MyTestRepositoryFolders.LoginOrRegisterPageContentFolder _loginorregisterpagecontent;

            /// <summary>
            /// Creates a new RegisterDropboxPersonalMicrosof  folder.
            /// </summary>
            public RegisterDropboxPersonalMicrosofAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterDropboxPersonalMicrosof", "/form[@title>'Register - Dropbox - Personal']", parentFolder, 30000, null, true, "9469a224-bd77-41fa-b7b4-a304c1da3a81", "")
            {
                _loginorregisterpagecontent = new MyTestRepositoryFolders.LoginOrRegisterPageContentFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9469a224-bd77-41fa-b7b4-a304c1da3a81")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9469a224-bd77-41fa-b7b4-a304c1da3a81")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginOrRegisterPageContent folder.
            /// </summary>
            [RepositoryFolder("5d27ee3f-3c94-46d7-b17f-48131f66bc1f")]
            public virtual MyTestRepositoryFolders.LoginOrRegisterPageContentFolder LoginOrRegisterPageContent
            {
                get { return _loginorregisterpagecontent; }
            }
        }

        /// <summary>
        /// The LoginOrRegisterPageContentFolder folder.
        /// </summary>
        [RepositoryFolder("5d27ee3f-3c94-46d7-b17f-48131f66bc1f")]
        public partial class LoginOrRegisterPageContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _continueInfo;
            RepoItemInfo _susiemail12233782113174296inputerrorInfo;
            RepoItemInfo _susiemail12233782113174296Info;

            /// <summary>
            /// Creates a new LoginOrRegisterPageContent  folder.
            /// </summary>
            public LoginOrRegisterPageContentFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginOrRegisterPageContent", "container[@name>'Register - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']//container/text[@name='Register - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']", parentFolder, 30000, null, false, "5d27ee3f-3c94-46d7-b17f-48131f66bc1f", "")
            {
                _continueInfo = new RepoItemInfo(this, "Continue", ".//button[@name='Continue']/?/?/text[@name='Continue']", "", 30000, null, "e5f6489c-ad07-4797-8b9d-4960bb4a4ab3");
                _susiemail12233782113174296inputerrorInfo = new RepoItemInfo(this, "SusiEmail12233782113174296InputError", ".//container[@automationid~'susi_email']", "", 30000, null, "71a887cc-99a7-4fdc-8bd0-88c9258d0608");
                _susiemail12233782113174296Info = new RepoItemInfo(this, "SusiEmail12233782113174296", ".//text[@automationid~'susi_email']", "", 30000, null, "6a88bfb2-627c-4f3a-8827-fe9bd2b21655");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5d27ee3f-3c94-46d7-b17f-48131f66bc1f")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5d27ee3f-3c94-46d7-b17f-48131f66bc1f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("e5f6489c-ad07-4797-8b9d-4960bb4a4ab3")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("e5f6489c-ad07-4797-8b9d-4960bb4a4ab3")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The SusiEmail12233782113174296InputError item.
            /// </summary>
            [RepositoryItem("71a887cc-99a7-4fdc-8bd0-88c9258d0608")]
            public virtual Ranorex.Container SusiEmail12233782113174296InputError
            {
                get
                {
                    return _susiemail12233782113174296inputerrorInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SusiEmail12233782113174296InputError item info.
            /// </summary>
            [RepositoryItemInfo("71a887cc-99a7-4fdc-8bd0-88c9258d0608")]
            public virtual RepoItemInfo SusiEmail12233782113174296InputErrorInfo
            {
                get
                {
                    return _susiemail12233782113174296inputerrorInfo;
                }
            }

            /// <summary>
            /// The SusiEmail12233782113174296 item.
            /// </summary>
            [RepositoryItem("6a88bfb2-627c-4f3a-8827-fe9bd2b21655")]
            public virtual Ranorex.Text SusiEmail12233782113174296
            {
                get
                {
                    return _susiemail12233782113174296Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SusiEmail12233782113174296 item info.
            /// </summary>
            [RepositoryItemInfo("6a88bfb2-627c-4f3a-8827-fe9bd2b21655")]
            public virtual RepoItemInfo SusiEmail12233782113174296Info
            {
                get
                {
                    return _susiemail12233782113174296Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
