///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace T14
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the T14Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d828ae8b-4b2c-43cd-95f3-1e0e0759fb48")]
    public partial class T14Repository : RepoGenBaseFolder
    {
        static T14Repository instance = new T14Repository();
        T14RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        T14RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder _logindropboxpersonalmicrosofte;

        /// <summary>
        /// Gets the singleton class instance representing the T14Repository element repository.
        /// </summary>
        [RepositoryFolder("d828ae8b-4b2c-43cd-95f3-1e0e0759fb48")]
        public static T14Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public T14Repository() 
            : base("T14Repository", "/", null, 0, false, "d828ae8b-4b2c-43cd-95f3-1e0e0759fb48", ".\\RepositoryImages\\T14Repositoryd828ae8b.rximgres")
        {
            _applicationundertest = new T14RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _logindropboxpersonalmicrosofte = new T14RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d828ae8b-4b2c-43cd-95f3-1e0e0759fb48")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("f7860e81-50db-4b39-9be5-c9cad345356c")]
        public virtual T14RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The LoginDropboxPersonalMicrosoftE folder.
        /// </summary>
        [RepositoryFolder("6e6a860d-06ae-423e-a3e3-2ff6880ff251")]
        public virtual T14RepositoryFolders.LoginDropboxPersonalMicrosoftEAppFolder LoginDropboxPersonalMicrosoftE
        {
            get { return _logindropboxpersonalmicrosofte; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class T14RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("f7860e81-50db-4b39-9be5-c9cad345356c")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.dropbox.com']", parentFolder, 30000, null, false, "f7860e81-50db-4b39-9be5-c9cad345356c", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f7860e81-50db-4b39-9be5-c9cad345356c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f7860e81-50db-4b39-9be5-c9cad345356c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The LoginDropboxPersonalMicrosoftEAppFolder folder.
        /// </summary>
        [RepositoryFolder("6e6a860d-06ae-423e-a3e3-2ff6880ff251")]
        public partial class LoginDropboxPersonalMicrosoftEAppFolder : RepoGenBaseFolder
        {
            T14RepositoryFolders.SidebarContentsSplitViewFolder _sidebarcontentssplitview;

            /// <summary>
            /// Creates a new LoginDropboxPersonalMicrosoftE  folder.
            /// </summary>
            public LoginDropboxPersonalMicrosoftEAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginDropboxPersonalMicrosoftE", "/form[@title>'Login - Dropbox - Personal']", parentFolder, 30000, null, true, "6e6a860d-06ae-423e-a3e3-2ff6880ff251", "")
            {
                _sidebarcontentssplitview = new T14RepositoryFolders.SidebarContentsSplitViewFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6e6a860d-06ae-423e-a3e3-2ff6880ff251")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6e6a860d-06ae-423e-a3e3-2ff6880ff251")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SidebarContentsSplitView folder.
            /// </summary>
            [RepositoryFolder("df8c744f-d2d3-4a85-a528-03c34bc0b4c7")]
            public virtual T14RepositoryFolders.SidebarContentsSplitViewFolder SidebarContentsSplitView
            {
                get { return _sidebarcontentssplitview; }
            }
        }

        /// <summary>
        /// The SidebarContentsSplitViewFolder folder.
        /// </summary>
        [RepositoryFolder("df8c744f-d2d3-4a85-a528-03c34bc0b4c7")]
        public partial class SidebarContentsSplitViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _susiemail06620637371151306Info;
            RepoItemInfo _welcomebackInfo;
            RepoItemInfo _continueInfo;

            /// <summary>
            /// Creates a new SidebarContentsSplitView  folder.
            /// </summary>
            public SidebarContentsSplitViewFolder(RepoGenBaseFolder parentFolder) :
                    base("SidebarContentsSplitView", "container[@name>'Login - Dropbox - Microsoft']//container[@classname='BrowserView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']/container[@classname='SidebarContentsSplitView']", parentFolder, 30000, null, false, "df8c744f-d2d3-4a85-a528-03c34bc0b4c7", "")
            {
                _susiemail06620637371151306Info = new RepoItemInfo(this, "SusiEmail06620637371151306", ".//container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//container[@classname='_field-input-wrapper_4srl7_50']/text[@automationid~'susi_email']", "", 30000, null, "05fb4cae-bcf2-4a93-965c-e7372ab87cab");
                _welcomebackInfo = new RepoItemInfo(this, "WelcomeBack", ".//container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//text[@name='Welcome back']", "", 30000, null, "dd71c4d8-7537-4167-9e0f-ecdeb6e6a93c");
                _continueInfo = new RepoItemInfo(this, "Continue", "container[@classname='SplitWindowContainerView']/?/?/container/text[@name='Login - Dropbox']/?/?/container[@automationid='root']/container[@automationid='page-content']/container[@automationid='login-or-register-page-content']//button[@name='Continue']/?/?/text[@name='Continue']", "", 30000, null, "88b295b7-64d5-4297-ad39-536256609e1e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("df8c744f-d2d3-4a85-a528-03c34bc0b4c7")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("df8c744f-d2d3-4a85-a528-03c34bc0b4c7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SusiEmail06620637371151306 item.
            /// </summary>
            [RepositoryItem("05fb4cae-bcf2-4a93-965c-e7372ab87cab")]
            public virtual Ranorex.Text SusiEmail06620637371151306
            {
                get
                {
                    return _susiemail06620637371151306Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SusiEmail06620637371151306 item info.
            /// </summary>
            [RepositoryItemInfo("05fb4cae-bcf2-4a93-965c-e7372ab87cab")]
            public virtual RepoItemInfo SusiEmail06620637371151306Info
            {
                get
                {
                    return _susiemail06620637371151306Info;
                }
            }

            /// <summary>
            /// The WelcomeBack item.
            /// </summary>
            [RepositoryItem("dd71c4d8-7537-4167-9e0f-ecdeb6e6a93c")]
            public virtual Ranorex.Text WelcomeBack
            {
                get
                {
                    return _welcomebackInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The WelcomeBack item info.
            /// </summary>
            [RepositoryItemInfo("dd71c4d8-7537-4167-9e0f-ecdeb6e6a93c")]
            public virtual RepoItemInfo WelcomeBackInfo
            {
                get
                {
                    return _welcomebackInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("88b295b7-64d5-4297-ad39-536256609e1e")]
            public virtual Ranorex.Text Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("88b295b7-64d5-4297-ad39-536256609e1e")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
