///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace T17
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AppleLogin recording.
    /// </summary>
    [TestModule("1ac14b31-d471-484b-b113-3a391f8db853", ModuleType.Recording, 1)]
    public partial class AppleLogin : ITestModule
    {
        /// <summary>
        /// Holds an instance of the T17Repository repository.
        /// </summary>
        public static T17Repository repo = T17Repository.Instance;

        static AppleLogin instance = new AppleLogin();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AppleLogin()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AppleLogin Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginDropboxPersonalMicrosoftE.ContinueWithApple' at 181;24.", repo.LoginDropboxPersonalMicrosoftE.ContinueWithAppleInfo, new RecordItemIndex(0));
            repo.LoginDropboxPersonalMicrosoftE.ContinueWithApple.Click("181;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Use your Apple ID to sign in to Dropbox.') on item 'SignInWithAppleIDPersonalMicro.UseYourAppleIDToSignInToDropbox'.", repo.SignInWithAppleIDPersonalMicro.UseYourAppleIDToSignInToDropboxInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.SignInWithAppleIDPersonalMicro.UseYourAppleIDToSignInToDropboxInfo, "Text", "Use your Apple ID to sign in to Dropbox.");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
